"""
Render the hardened user_project_wrapper GDS as a colored PNG using KLayout.

Auto-generated by vyges-soc-generator — do not hand-edit. This is the
proof-of-completion picture: it loads the *actual* hardened wrapper GDS and
renders it with the sky130A.lyp layer colors so reviewers can see the real
silicon-ready layout.

Companion: docs/user_project_wrapper_floorplan.svg is the *planned* floorplan
generated at soc-generator time and ships before any tool runs. The PNG this
script produces is the post-flow snapshot of what the design actually
hardened to. Embed both in the README — they tell two different stories.

Run from the repo root after `cf harden user_project_wrapper` (or after
`run-openlane.sh user_project_wrapper`):

    klayout -z -nc -rx -r openlane/user_project_wrapper/render_hardened_layout.py

KLayout binary locations (the script does not enforce a path — invoke
whichever one you have):
    macOS:           /Applications/KLayout/klayout.app/Contents/MacOS/klayout
    OpenLane2:       inside ghcr.io/efabless/openlane2:2.3.10  (klayout in $PATH)
    LibreLane:       inside the LibreLane container             (klayout in $PATH)

Output: docs/user_project_wrapper_layout.png
"""

import glob
import os
import sys

import pya

# Resolve repo root: this script lives in openlane/user_project_wrapper/
SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
REPO_ROOT  = os.path.abspath(os.path.join(SCRIPT_DIR, "..", ".."))
GDS        = os.path.join(REPO_ROOT, "gds/user_project_wrapper.gds")
OUT        = os.path.join(REPO_ROOT, "docs/user_project_wrapper_layout.png")

if not os.path.exists(GDS):
    sys.stderr.write(
        "ERROR: hardened GDS not found at {}\n"
        "       Run 'cf harden user_project_wrapper' (or "
        "scripts/run-openlane.sh user_project_wrapper) first.\n".format(GDS)
    )
    pya.Application.instance().exit(1)

# ── Locate sky130A.lyt + sky130A.lyp from the PDK install ───────────────────
# KLayout needs the *technology* (.lyt) registered before loading the GDS so
# that the GDS layers get associated with the right colour scheme. Loading
# only the .lyp afterwards via view.load_layer_props() does not work in
# headless mode — every layer ends up rendering in a single fallback colour
# and the result is a solid magenta blob.
#
# Search the standard ChipFoundry CLI (ciel), volare, and in-repo PDK
# locations. The .lyt sits next to the .lyp under
#   <pdk_root>/sky130A/libs.tech/klayout/tech/sky130A.{lyt,lyp}
TECH_PATTERNS = [
    os.path.expanduser("~/.ciel/ciel/sky130/versions/*/sky130A/libs.tech/klayout/tech/sky130A.lyt"),
    os.path.expanduser("~/.volare/volare/sky130/versions/*/sky130A/libs.tech/klayout/tech/sky130A.lyt"),
    os.path.join(REPO_ROOT, "dependencies/pdks/ciel/sky130/versions/*/sky130A/libs.tech/klayout/tech/sky130A.lyt"),
    os.path.join(REPO_ROOT, "dependencies/pdks/volare/sky130/versions/*/sky130A/libs.tech/klayout/tech/sky130A.lyt"),
    "/foss/pdks/sky130A/libs.tech/klayout/tech/sky130A.lyt",
]

lyt = None
for pattern in TECH_PATTERNS:
    matches = sorted(glob.glob(pattern))
    if matches:
        lyt = matches[-1]   # newest version if more than one
        break

if lyt:
    lyp = os.path.join(os.path.dirname(lyt), "sky130A.lyp")
    print("Found sky130A technology:", lyt)
else:
    lyp = None
    sys.stderr.write(
        "WARNING: sky130A.lyt not found — rendering with default colours.\n"
        "         Searched: " + ", ".join(TECH_PATTERNS) + "\n"
    )

# ── Register the sky130A technology BEFORE loading the GDS ──────────────────
# This is the part that makes headless rendering work. Without it, KLayout
# loads the GDS with auto-generated layer assignments that don't match the
# .lyp source specs, so the colours never apply.
if lyt:
    tech = pya.Technology()
    tech.load(lyt)
    # Register so subsequent layout loads can pick it up by name.
    try:
        pya.Technology.register_technology(tech)
    except AttributeError:
        # Older KLayout: registration is implicit on load.
        pass

# ── Load the layout (with technology hint when available) ───────────────────
mw = pya.Application.instance().main_window()
if lyt:
    options = pya.LoadLayoutOptions()
    try:
        mw.load_layout(GDS, options, 0, "sky130A")
    except (RuntimeError, TypeError):
        # Older KLayout signatures fall back to the basic two-arg form.
        mw.load_layout(GDS, 0)
else:
    mw.load_layout(GDS, 0)

view = mw.current_view()
view.max_hier()

# Belt-and-braces: also explicitly load the .lyp on the view, with
# add_default=True so any layers from the .lyp template that aren't yet
# present in the view get added with their declared colours.
if lyp and os.path.exists(lyp):
    try:
        view.load_layer_props(lyp, True, True)   # all_views, add_default
    except TypeError:
        try:
            view.load_layer_props(lyp, True)
        except TypeError:
            view.load_layer_props(lyp)
    print("Loaded layer properties:", lyp)

view.zoom_fit()

os.makedirs(os.path.dirname(OUT), exist_ok=True)
view.save_image(OUT, 1600, 1920)
print("Wrote:", OUT)
pya.Application.instance().exit(0)