// @generated by vyges-soc-generator — do not hand-edit
//
// edge_sensor — reset propagation test SV wrapper
//
// Same shape as tb_smoke.sv: instantiates top_edge_sensor_sim, ties off
// external pins, exposes the Ibex instruction-fetch PC as dbg_pc_o, and
// loads the firmware image (boot_rom.hex) into the CPU's local boot ROM
// via a hierarchical $readmemh on the first posedge clk_i.
//
// The reset propagation test pulses rst_ni from the cocotb side; this
// wrapper just provides the DUT instance + boot ROM load mechanism.

`timescale 1ns / 1ps

module tb_reset (
    input  wire        clk_i,
    input  wire        rst_ni,
    output wire [31:0] dbg_pc_o
);

`ifndef GLS_CARAVEL
    // ── Default mode: RTL or generic GLS ─────────────────────────────────
    wire uart_tx;
    wire spi_sclk, spi_cs_n, spi_mosi;
    wire irq_ext;

    top_edge_sensor_sim dut (
        .clk_i      (clk_i),
        .rst_ni     (rst_ni),
        .uart_tx_o  (uart_tx),
        .uart_rx_i  (1'b1),
        .spi_sclk_o (spi_sclk),
        .spi_cs_no  (spi_cs_n),
        .spi_mosi_o (spi_mosi),
        .spi_miso_i (1'b0),
        .irq_ext_o  (irq_ext)
    );
`else
    // ── Caravel GLS mode: instantiate user_project_wrapper ───────────────
    // See tb_smoke.sv header for the rationale.
    wire [37:0]  io_out, io_oeb;
    wire [127:0] la_data_out;
    wire [31:0]  wbs_dat_o;
    wire         wbs_ack_o;
    wire [2:0]   user_irq;

    user_project_wrapper dut (
        .wb_clk_i    (clk_i),
        .wb_rst_i    (~rst_ni),
        .wbs_stb_i   (1'b0),
        .wbs_cyc_i   (1'b0),
        .wbs_we_i    (1'b0),
        .wbs_sel_i   (4'b0),
        .wbs_dat_i   (32'b0),
        .wbs_adr_i   (32'b0),
        .wbs_ack_o   (wbs_ack_o),
        .wbs_dat_o   (wbs_dat_o),
        .la_data_in  (128'b0),
        .la_data_out (la_data_out),
        .la_oenb     (128'b0),
        .io_in       (38'b0),
        .io_out      (io_out),
        .io_oeb      (io_oeb),
        .analog_io   (),
        .user_clock2 (clk_i),
        .user_irq    (user_irq)
    );
`endif

    assign dbg_pc_o = dut.u_ibex.instr_addr;

    // ── Boot ROM load ──────────────────────────────────────────────────
    // Load the firmware image. The CPU's local boot ROM is 32 KB and is
    // not affected by reset (the array contents are loaded once at sim
    // start and survive reset cycles), so the firmware stays valid
    // across the reset pulses driven from the cocotb test.
    reg boot_rom_loaded = 1'b0;
    always @(posedge clk_i) begin
        if (!boot_rom_loaded) begin
            $readmemh("../../../boot_rom.hex", dut.u_ibex.boot_rom);
            $display("[tb_reset] loaded boot_rom.hex; boot_rom[0]=%08h", dut.u_ibex.boot_rom[0]);
            boot_rom_loaded <= 1'b1;
        end
    end

endmodule