"""
edge_sensor — reset propagation test (cocotb)
==================================================

@generated by vyges-soc-generator — do not hand-edit

Verifies that asserting rst_ni at any point during firmware execution
cleanly resets the CPU back to the boot entry address, and that the CPU
resumes executing the firmware once reset deasserts. Catches the family
of integration bugs where reset is wired to the CPU but not propagated
to a downstream module (so the CPU restarts but the bus / peripheral /
register state stays stale and the second boot diverges).

This is the L1 reset-distribution check in the layered SoC verification
stack. Functional correctness of individual reset logic inside each IP
is the IP repo's responsibility (L0).

Pass criteria:
  1. After the initial reset deasserts, the CPU PC advances past the
     boot entry address (initial boot proves the firmware is loaded).
  2. Asserting rst_ni again drops the PC back into the boot-ROM window
     (reset reached the CPU's instruction-fetch path).
  3. After the second reset deasserts, the PC advances *forward* again
     past the boot entry — proving the CPU not only reset but also
     successfully resumed execution from a clean state.
  4. The same recovery happens across multiple reset cycles, not just
     one (catches state that survives one reset but breaks on the
     second cycle).
"""

import cocotb
from cocotb.clock import Clock
from cocotb.triggers import RisingEdge, ClockCycles


CLK_PERIOD_NS    = 20     # core clock period
INITIAL_RST_CYC  = 20                        # initial reset window
RUN_CYCLES       = 5_000                     # firmware run window between resets
RESET_PULSE_CYC  = 30                        # reset hold time per pulse
NUM_RESET_CYCLES = 3                         # number of reset/run cycles to exercise
BOOT_ENTRY       = 0x00008000       # CPU boot_addr_i
BOOT_ROM_END     = BOOT_ENTRY + 0x10000      # local boot ROM aliases at this size

# A PC is "in the boot ROM window" if it lies between BOOT_ENTRY and the
# end of the local boot ROM. Ibex's instruction-fetch may briefly speculate
# above this range, so we use a relaxed check that catches both the
# normal case and the wrapped-instruction-fetch case.
def _in_boot_window(pc: int) -> bool:
    return BOOT_ENTRY <= pc < BOOT_ROM_END


async def _drive_reset_pulse(dut, hold_cycles: int):
    """Hold rst_ni low for `hold_cycles`, then release on the next posedge."""
    dut.rst_ni.value = 0
    await ClockCycles(dut.clk_i, hold_cycles)
    dut.rst_ni.value = 1
    await RisingEdge(dut.clk_i)


@cocotb.test()
async def reset_propagation(dut):
    """edge_sensor CPU resets cleanly across multiple reset cycles."""
    cocotb.start_soon(Clock(dut.clk_i, CLK_PERIOD_NS, units="ns").start())

    # ── Initial boot ───────────────────────────────────────────────────────
    await _drive_reset_pulse(dut, INITIAL_RST_CYC)
    dut._log.info(
        f"[reset] initial boot — running {RUN_CYCLES} cycles to confirm "
        f"firmware loads (boot_entry=0x{BOOT_ENTRY:08x})"
    )
    await ClockCycles(dut.clk_i, RUN_CYCLES)
    pc_after_initial = int(dut.dbg_pc_o.value)
    dut._log.info(f"[reset] PC after initial boot: 0x{pc_after_initial:08x}")
    assert pc_after_initial > BOOT_ENTRY, (
        f"CPU failed to advance past boot entry on initial boot. "
        f"PC=0x{pc_after_initial:08x}, expected > 0x{BOOT_ENTRY:08x}. "
        "Either firmware did not load or the CPU is held in reset."
    )

    # ── Repeated reset/run cycles ──────────────────────────────────────────
    # Each iteration: pulse reset, verify PC drops back to the boot window,
    # release reset, verify PC advances past boot entry again. Confirms the
    # CPU + boot ROM + execution path all recover cleanly across N resets.
    for cycle in range(NUM_RESET_CYCLES):
        dut._log.info(f"[reset] cycle {cycle+1}/{NUM_RESET_CYCLES}: asserting reset")
        dut.rst_ni.value = 0
        await ClockCycles(dut.clk_i, RESET_PULSE_CYC)

        pc_during_reset = int(dut.dbg_pc_o.value)
        dut._log.info(
            f"[reset] cycle {cycle+1}: PC during reset hold = 0x{pc_during_reset:08x}"
        )
        assert _in_boot_window(pc_during_reset), (
            f"After RESET pulse #{cycle+1}, PC=0x{pc_during_reset:08x} is "
            f"outside the boot-ROM window [0x{BOOT_ENTRY:08x}, 0x{BOOT_ROM_END:08x}). "
            "Reset is not propagating to the CPU instruction-fetch path."
        )

        dut.rst_ni.value = 1
        await RisingEdge(dut.clk_i)
        dut._log.info(f"[reset] cycle {cycle+1}: reset released, running {RUN_CYCLES} cycles")
        await ClockCycles(dut.clk_i, RUN_CYCLES)

        pc_after_recovery = int(dut.dbg_pc_o.value)
        dut._log.info(
            f"[reset] cycle {cycle+1}: PC after recovery = 0x{pc_after_recovery:08x}"
        )
        assert pc_after_recovery > BOOT_ENTRY, (
            f"After RESET cycle #{cycle+1}, CPU did not resume execution. "
            f"PC=0x{pc_after_recovery:08x}, expected > 0x{BOOT_ENTRY:08x}. "
            "Reset propagated but the CPU is now stuck — likely a peripheral "
            "or bus state that survived reset and now blocks the CPU."
        )

    dut._log.info(
        f"[reset] PASS — CPU recovered cleanly across {NUM_RESET_CYCLES} reset cycles"
    )