// @generated by vyges-soc-generator — do not hand-edit
//
// edge_sensor — bus walk test SV wrapper
//
// Thin SystemVerilog wrapper around top_edge_sensor_sim for the cocotb
// bus connectivity walk. Same shape as tb_smoke.sv but loads the
// generated busread.hex test program (instead of the normal firmware
// boot_rom.hex) into the CPU's local boot ROM.
//
// busread.hex is a tiny RISC-V program emitted by the soc-generator at
// generation time, derived from the address map. It does:
//   for each peripheral: lui t0, base; lw t1, 0(t0)
//   halt:                j halt
//
// If every peripheral's bus path is reachable, the CPU runs all the lws
// and parks at the halt loop. If any read stalls, PC freezes mid-program
// and the cocotb test fails with the stalled PC.

`timescale 1ns / 1ps

module tb_buswalk (
    input  wire        clk_i,
    input  wire        rst_ni,
    output wire [31:0] dbg_pc_o
);

`ifndef GLS_CARAVEL
    // ── Default mode: RTL or generic GLS ─────────────────────────────────
    wire uart_tx;
    wire spi_sclk, spi_cs_n, spi_mosi;
    wire irq_ext;

    top_edge_sensor_sim dut (
        .clk_i      (clk_i),
        .rst_ni     (rst_ni),
        .uart_tx_o  (uart_tx),
        .uart_rx_i  (1'b1),
        .spi_sclk_o (spi_sclk),
        .spi_cs_no  (spi_cs_n),
        .spi_mosi_o (spi_mosi),
        .spi_miso_i (1'b0),
        .irq_ext_o  (irq_ext)
    );
`else
    // ── Caravel GLS mode: instantiate user_project_wrapper ───────────────
    // See tb_smoke.sv header for the rationale. Same hierarchical access
    // path to dut.u_ibex.boot_rom still works
    // because the wrapper instantiates rv_core_ibex_tlul as u_ibex with
    // the (* keep *) attributes preserving boot_rom + instr_addr.
    wire [37:0]  io_out, io_oeb;
    wire [127:0] la_data_out;
    wire [31:0]  wbs_dat_o;
    wire         wbs_ack_o;
    wire [2:0]   user_irq;

    user_project_wrapper dut (
        .wb_clk_i    (clk_i),
        .wb_rst_i    (~rst_ni),
        .wbs_stb_i   (1'b0),
        .wbs_cyc_i   (1'b0),
        .wbs_we_i    (1'b0),
        .wbs_sel_i   (4'b0),
        .wbs_dat_i   (32'b0),
        .wbs_adr_i   (32'b0),
        .wbs_ack_o   (wbs_ack_o),
        .wbs_dat_o   (wbs_dat_o),
        .la_data_in  (128'b0),
        .la_data_out (la_data_out),
        .la_oenb     (128'b0),
        .io_in       (38'b0),
        .io_out      (io_out),
        .io_oeb      (io_oeb),
        .analog_io   (),
        .user_clock2 (clk_i),
        .user_irq    (user_irq)
    );
`endif

    assign dbg_pc_o = dut.u_ibex.instr_addr;

    // ── Boot ROM load ──────────────────────────────────────────────────
    // Load the bus-walk test program into the CPU's local boot ROM. Same
    // mechanism as the smoke test (one-shot always-block on first posedge,
    // works around top-down initial-block ordering races).
    reg test_program_loaded = 1'b0;
    always @(posedge clk_i) begin
        if (!test_program_loaded) begin
            $readmemh("busread.hex", dut.u_ibex.boot_rom);
            $display("[tb_buswalk] loaded busread.hex; boot_rom[0]=%08h", dut.u_ibex.boot_rom[0]);
            test_program_loaded <= 1'b1;
        end
    end

endmodule