"""
edge_sensor — bus connectivity walk (cocotb)
================================================

@generated by vyges-soc-generator — do not hand-edit

Verifies that the edge_sensor SoC's TL-UL crossbar correctly routes bus
transactions to every peripheral declared in the address map. Pass = the
CPU successfully reads from each peripheral's base address without
stalling.

This is the L1 connectivity test in the layered SoC verification stack:

  L0 — IP unit tests        — IP repo's responsibility (assumed validated)
  L1 — SoC connectivity     — THIS TEST: address decode + bus reachability
  L2 — SoC interrupts       — separate test (planned)
  L3 — SoC firmware smoke   — tb/cocotb/smoke/  (boots real firmware)
  L4 — SoC GLS              — same tests against verilog/gl/

How it works
------------
The soc-generator emits a tiny RISC-V test program (busread.hex) at
generation time, derived from the address map. The program does:

  for each peripheral in the spec:
      lui   t0, <peripheral base>>>12
      lw    t1, 0(t0)              # bus read — stalls forever if decode broken
  halt:
      j halt                       # infinite loop at known PC

The cocotb test loads busread.hex into the CPU's local boot ROM (instead
of the normal firmware), runs the CPU, and asserts the PC reaches the
halt address within the deadline. If any peripheral's bus path is broken
(wrong xbar decode, missing slave, or hung response), the lw instruction
to that peripheral never returns and the PC freezes before reaching
halt — test fails with the stalled PC pointing at the broken peripheral.

Pass criteria:
  1. CPU comes out of reset and starts executing the test program.
  2. PC reaches HALT_ADDR within MAX_CYCLES (every peripheral was read).
  3. PC stays at HALT_ADDR after reaching it (the infinite loop is stable).
"""

import cocotb
from cocotb.clock import Clock
from cocotb.triggers import RisingEdge, ClockCycles


CLK_PERIOD_NS  = 20     # core clock period
RESET_CYCLES   = 20                        # cycles to hold reset asserted
MAX_CYCLES     = 200_000                   # bring-up budget for the bus walk
BOOT_ENTRY     = 0x00008000       # CPU boot_addr_i
HALT_ADDR      = 0x00008020       # PC of the wfi halt instruction

# Peripherals walked by the generated test program, in execution order.
# Each entry is (instance_name, base_address).
PERIPHERALS = [    ("u_uart", 0x40000000),    ("u_spi_host", 0x40200000),    ("u_plic", 0x40300000),    ("u_fft", 0x40100000),]


async def _drive_reset(dut):
    """Apply reset for RESET_CYCLES, then deassert."""
    dut.rst_ni.value = 0
    await ClockCycles(dut.clk_i, RESET_CYCLES)
    dut.rst_ni.value = 1
    await RisingEdge(dut.clk_i)


@cocotb.test()
async def buswalk(dut):
    """edge_sensor CPU reads each peripheral's base address via the bus."""
    cocotb.start_soon(Clock(dut.clk_i, CLK_PERIOD_NS, units="ns").start())

    await _drive_reset(dut)
    dut._log.info(
        f"[buswalk] reset released — running bus walk for "
        f"{len(PERIPHERALS)} peripherals "
        f"(boot_entry={BOOT_ENTRY:#010x}, halt_addr={HALT_ADDR:#010x})"
    )
    for inst, base in PERIPHERALS:
        dut._log.info(f"[buswalk]   walking {inst:18s} @ {base:#010x}")

    # ── Run until max PC reaches halt address (or beyond) ─────────────────
    # We track the maximum instruction-fetch PC seen during the run rather
    # than the latest sampled value, because the Ibex instr_addr signal can
    # advance speculatively past a stalled data-port load and then 'wrap'
    # back to earlier addresses (the local boot ROM uses instr_addr[14:2]
    # for indexing, so PCs above 0x10000 alias back to ROM word 0). The
    # ground truth question is: did the CPU EVER reach an address at or
    # past the halt instruction? If yes, every preceding lw completed —
    # which is what we wanted to verify.
    max_pc = 0
    halted = False
    for n in range(0, MAX_CYCLES, 1_000):
        await ClockCycles(dut.clk_i, 1_000)
        pc = int(dut.dbg_pc_o.value)
        if pc > max_pc:
            max_pc = pc
        # Check if PC is at or past halt (within the boot-ROM window)
        if BOOT_ENTRY <= pc < (BOOT_ENTRY + 0x10000) and pc >= HALT_ADDR:
            halted = True
            dut._log.info(
                f"[buswalk] PASS — PC reached 0x{pc:08x} >= halt at "
                f"0x{HALT_ADDR:08x} (cycle ~{n+1_000})"
            )
            break

    if not halted:
        # The CPU is stuck before reaching the halt instruction. Try to
        # localise which peripheral is the culprit by mapping the PC back
        # into the program window. The generated test program is laid out
        # as 2-instruction sequences (lui + lw) per peripheral starting at
        # BOOT_ENTRY, so each peripheral occupies 8 bytes of program space.
        # PCs above the boot-ROM window are wrapped via instr_addr[14:2].
        local_pc = (max_pc - BOOT_ENTRY) & 0x1FFF
        if local_pc < 8 * len(PERIPHERALS):
            stuck_idx = local_pc // 8
            stuck_periph = PERIPHERALS[stuck_idx][0]
        else:
            stuck_periph = "<unknown / past program window>"

        assert False, (
            f"buswalk timed out after {MAX_CYCLES} cycles: max_pc seen "
            f"= 0x{max_pc:08x}, never reached halt at 0x{HALT_ADDR:08x}. "
            f"Likely stuck reading peripheral '{stuck_periph}'. Check the "
            f"xbar address decode and the peripheral's TL-UL response path."
        )

    dut._log.info(
        f"[buswalk] PASS — all {len(PERIPHERALS)} peripherals read OK "
        f"(max_pc=0x{max_pc:08x}, halt=0x{HALT_ADDR:08x})"
    )