#!/usr/bin/env bash
# @generated by vyges-soc-generator
#
# Harden all macros bottom-up, then assemble the Caravel user_project_wrapper.
#
# Each macro's openlane/<macro>/config.json contains the proven floorplan,
# placement coordinates, SRAM blackbox handling, and timing constraints
# used to produce the GDS files shipped in gds/. Running this script
# reproduces the hardening flow from the committed RTL + configs.
#
# Prerequisites:
#   - OpenLane 2.3.10+ (or LibreLane) installed via Docker/Podman or natively
#   - Sky130A PDK installed via ciel or volare
#   - For SRAM-containing macros (fft_ctrl_tlul): patched SRAM liberty with
#     max_transition relaxed to 0.50ns (see openlane/fft_ctrl_tlul/config.json)
#
# Usage:
#   bash openlane/run-openlane.sh                # harden all macros + wrapper
#   bash openlane/run-openlane.sh xbar_main      # harden a single macro
#
# The wrapper (user_project_wrapper) uses SYNTH_ELABORATE_ONLY and expects
# all sub-macro GDS/LEF/LIB to be present before it runs. The harden order
# below ensures dependencies are built first.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"

# Bottom-up harden order: sub-macros first, wrapper last.
# user_proj_example is the Caravel template's default and is skipped.
HARDEN_ORDER=(
    xbar_main
    uart
    spi_host_lite
    rv_plic_lite
    rv_core_ibex_tlul
    fft_ctrl_tlul
    edge_sensor_glue
    user_project_wrapper
)

harden_macro() {
    local macro="$1"
    local config="${SCRIPT_DIR}/${macro}/config.json"

    if [ ! -f "$config" ]; then
        echo "ERROR: config not found: $config" >&2
        return 1
    fi

    echo ""
    echo "=== Hardening: ${macro} ==="
    echo "    config: ${config}"

    # Prefer cf harden (ChipFoundry CLI) if available, fall back to openlane
    if command -v cf &>/dev/null; then
        cf harden "$macro"
    elif command -v openlane &>/dev/null; then
        openlane "$config"
    else
        echo "ERROR: neither 'cf' nor 'openlane' found on PATH" >&2
        echo "       Install OpenLane 2: pip install openlane" >&2
        return 1
    fi

    echo "=== Done: ${macro} ==="
}

copy_views() {
    local macro="$1"
    local run_dir

    # Find the latest run directory
    run_dir=$(ls -td "${SCRIPT_DIR}/${macro}/runs/"*/ 2>/dev/null | head -1)
    if [ -z "$run_dir" ]; then
        echo "WARNING: no run directory found for ${macro}" >&2
        return 0
    fi

    echo "    Copying hardened views from ${run_dir}..."

    # GDS
    for f in "${run_dir}"final/gds/*.gds; do
        [ -f "$f" ] && cp "$f" "${REPO_ROOT}/gds/" && echo "      gds/$(basename "$f")"
    done

    # LEF
    for f in "${run_dir}"final/lef/*.lef; do
        [ -f "$f" ] && cp "$f" "${REPO_ROOT}/lef/" && echo "      lef/$(basename "$f")"
    done

    # GL netlist
    for f in "${run_dir}"final/nl/*.v "${run_dir}"final/verilog/gl/*.v; do
        [ -f "$f" ] && cp "$f" "${REPO_ROOT}/verilog/gl/" && echo "      verilog/gl/$(basename "$f")"
    done

    # SPEF (multi-corner)
    for f in "${run_dir}"final/spef/*/*.spef "${run_dir}"final/spef/*.spef; do
        [ -f "$f" ] && mkdir -p "${REPO_ROOT}/spef/multicorner" && cp "$f" "${REPO_ROOT}/spef/multicorner/" && echo "      spef/multicorner/$(basename "$f")"
    done

    # LIB
    for f in "${run_dir}"final/lib/*.lib "${run_dir}"final/lib/*/*.lib; do
        [ -f "$f" ] && mkdir -p "${REPO_ROOT}/lib" && cp "$f" "${REPO_ROOT}/lib/" && echo "      lib/$(basename "$f")"
    done
}

# ── Main ─────────────────────────────────────────────────────────────────

if [ $# -ge 1 ]; then
    # Single macro mode
    harden_macro "$1"
    copy_views "$1"
else
    # Full bottom-up harden
    echo "Hardening all macros in bottom-up order..."
    for macro in "${HARDEN_ORDER[@]}"; do
        harden_macro "$macro"
        copy_views "$macro"
    done
    echo ""
    echo "=== All macros hardened ==="
    echo "GDS files:"
    ls -lh "${REPO_ROOT}/gds/"*.gds 2>/dev/null || echo "  (none — check run directories)"
fi
