// © 2026 Vyges. All Rights Reserved. Generated by Vyges SoC Generator.
//
// Edge Sensor SoC — open-top enclosure for chipIgnite Caravel QFN-64
// reference board (60 × 50 mm, 4-layer FR4).
//
// Parameters derived from soc-spec.yaml pcba.asic.mechanical section.
// Designed for 3D printing (FDM/SLA) or CNC milling. Mounting via M3
// bolts through the PCB mounting holes into the enclosure standoffs.
//
// Usage:
//   openscad -o enclosure.stl enclosure.scad
//   openscad -o enclosure.step enclosure.scad   # requires OpenSCAD 2024+
//
// For motor/pump housing mounting: add M4 through-holes on the bottom
// face (not included — application-specific).

/* ── Board parameters (from soc-spec.yaml) ─────────────────────────── */

board_width       = 60;     // mm — pcba.asic.mechanical.outline.width_mm
board_height      = 50;     // mm — pcba.asic.mechanical.outline.height_mm
board_thickness   = 1.6;    // mm — pcba.asic.mechanical.thickness_mm
corner_radius     = 2;      // mm — pcba.asic.mechanical.outline.corner_radius_mm
component_clearance = 12;   // mm — pcba.asic.mechanical.enclosure.clearance_mm

/* ── Mounting holes (from soc-spec.yaml) ───────────────────────────── */

mount_hole_diameter = 3.2;  // mm — M3 clearance
mount_hole_count    = 4;    // corners pattern
mount_inset         = 4;    // mm from board edge to hole center

/* ── Enclosure parameters ──────────────────────────────────────────── */

wall_thickness    = 2.0;    // mm — enclosure wall
floor_thickness   = 2.0;    // mm — bottom plate
standoff_height   = 5.0;    // mm — clearance under board for bottom-side components
standoff_diameter = 6.0;    // mm — M3 standoff outer diameter
pcb_lip           = 1.0;    // mm — ledge that supports the PCB edge

/* ── Connector cutouts ─────────────────────────────────────────────── */
// USB-C on the south edge (centered)
usbc_width        = 10;     // mm
usbc_height       = 4;      // mm (above board surface)
usbc_center_x     = board_width / 2;

// Pmod 2×6 header on the east edge (centered)
pmod_width        = 16;     // mm
pmod_height       = 10;     // mm (above board surface — through-hole connector)
pmod_center_y     = board_height / 2;

/* ── Derived dimensions ────────────────────────────────────────────── */

interior_width  = board_width + 1.0;   // 0.5mm clearance each side
interior_height = board_height + 1.0;
interior_depth  = standoff_height + board_thickness + component_clearance;

exterior_width  = interior_width + 2 * wall_thickness;
exterior_height = interior_height + 2 * wall_thickness;
exterior_depth  = interior_depth + floor_thickness;

/* ── Modules ───────────────────────────────────────────────────────── */

module rounded_box(w, h, d, r) {
    hull() {
        for (x = [r, w - r])
            for (y = [r, h - r])
                translate([x, y, 0])
                    cylinder(h = d, r = r, $fn = 32);
    }
}

module enclosure_shell() {
    difference() {
        // Outer shell
        rounded_box(exterior_width, exterior_height, exterior_depth, corner_radius + wall_thickness);

        // Interior cavity (open top)
        translate([wall_thickness, wall_thickness, floor_thickness])
            rounded_box(interior_width, interior_height, interior_depth + 1, corner_radius);
    }
}

module standoff(x, y) {
    // Standoff cylinder from floor to board underside
    translate([wall_thickness + 0.5 + x, wall_thickness + 0.5 + y, floor_thickness]) {
        difference() {
            cylinder(h = standoff_height, d = standoff_diameter, $fn = 24);
            // M3 threaded hole (2.5mm pilot for self-tapping or heat-set insert)
            cylinder(h = standoff_height + 1, d = 2.5, $fn = 24);
        }
    }
}

module mounting_standoffs() {
    // Four corners pattern
    inset = mount_inset;
    standoff(inset, inset);
    standoff(board_width - inset, inset);
    standoff(inset, board_height - inset);
    standoff(board_width - inset, board_height - inset);
}

module connector_cutouts() {
    board_z = floor_thickness + standoff_height;

    // USB-C cutout — south edge (y = 0 side of the enclosure)
    translate([wall_thickness + 0.5 + usbc_center_x - usbc_width / 2,
               -1,
               board_z])
        cube([usbc_width, wall_thickness + 2, usbc_height + board_thickness]);

    // Pmod header cutout — east edge (x = board_width side)
    translate([wall_thickness + 0.5 + board_width - 1,
               wall_thickness + 0.5 + pmod_center_y - pmod_width / 2,
               board_z])
        cube([wall_thickness + 2, pmod_width, pmod_height + board_thickness]);
}

module pcb_support_ledge() {
    // Thin ledge along the inner walls that supports the PCB edges
    board_z = floor_thickness + standoff_height;
    translate([wall_thickness, wall_thickness, board_z - pcb_lip])
        difference() {
            rounded_box(interior_width, interior_height, pcb_lip, corner_radius);
            translate([pcb_lip, pcb_lip, -1])
                rounded_box(interior_width - 2 * pcb_lip,
                            interior_height - 2 * pcb_lip,
                            pcb_lip + 2,
                            max(0.1, corner_radius - pcb_lip));
        }
}

/* ── Branding ──────────────────────────────────────────────────────── */

branding_text     = "VYGES";
branding_subtext  = "Edge Sensor SoC";
branding_depth    = 0.6;    // mm — emboss height above surface
branding_font     = "Lato:style=Bold";

module branding() {
    // "VYGES" on the north wall exterior — readable from outside
    translate([exterior_width / 2, exterior_height + wall_thickness, exterior_depth * 0.55])
        rotate([90, 0, 180])
            translate([0, 0, -branding_depth])
                linear_extrude(height = branding_depth)
                    text(branding_text, size = 5, font = branding_font,
                         halign = "center", valign = "center", $fn = 32);

    // "Edge Sensor SoC" on the south wall exterior — no Z rotation (opposite face)
    translate([exterior_width / 2, -(wall_thickness), exterior_depth * 0.82])
        rotate([90, 0, 0])
            translate([0, 0, -branding_depth])
                linear_extrude(height = branding_depth)
                    text(branding_subtext, size = 3.5, font = branding_font,
                         halign = "center", valign = "center", $fn = 32);

    // Embossed on the interior floor (visible when looking into the open top)
    translate([exterior_width / 2, exterior_height / 2, floor_thickness])
        linear_extrude(height = branding_depth) {
            text(branding_text, size = 8, font = branding_font,
                 halign = "center", valign = "center", $fn = 32);
            translate([0, -7, 0])
                text(branding_subtext, size = 3.5, font = branding_font,
                     halign = "center", valign = "center", $fn = 32);
        }
}

/* ── Final assembly ────────────────────────────────────────────────── */

module enclosure() {
    difference() {
        union() {
            enclosure_shell();
            mounting_standoffs();
            pcb_support_ledge();
            branding();
        }
        connector_cutouts();
    }
}

// Render
enclosure();

/* ── Info echo ─────────────────────────────────────────────────────── */

echo(str("Enclosure exterior: ",
         exterior_width, " × ", exterior_height, " × ", exterior_depth, " mm"));
echo(str("Board position: z = ", floor_thickness + standoff_height, " mm from bottom"));
echo(str("Internal clearance above board: ", component_clearance, " mm"));
echo(str("Total height (open top): ", exterior_depth, " mm"));
