// edge_sensor_glue — Integration glue for edge_sensor SoC
//
// HAL architecture (see docs/glue-hal-design.md):
//   Layer 1: SoC Interface — target-agnostic port contract
//   Layer 2: Caravel I/O Adapter — target-specific mapping
//   Layer 3: This module — composition
//
// Generated by Vyges SoC Generator

`default_nettype none

module edge_sensor_glue (
    // ── Caravel-side ports (target adapter) ─────────────────────────────
    input  wire        wb_clk_i,
    input  wire        wb_rst_i,

    input  wire        wbs_stb_i,
    input  wire        wbs_cyc_i,
    input  wire        wbs_we_i,
    input  wire [3:0]  wbs_sel_i,
    input  wire [31:0] wbs_dat_i,
    input  wire [31:0] wbs_adr_i,
    output wire        wbs_ack_o,
    output wire [31:0] wbs_dat_o,

    input  wire [127:0] la_data_in,
    output wire [127:0] la_data_out,
    input  wire [127:0] la_oenb,

    input  wire [37:0] io_in,
    output wire [37:0] io_out,
    output wire [37:0] io_oeb,

    output wire [2:0]  user_irq,

    // ── SoC-side ports (soc_interface) ──────────────────────────────────
    // ════════════════════════════════════════════════════════════════════════
    // SoC Interface — edge_sensor
    // Target-agnostic external port contract
    // Generated by Vyges SoC Generator
    // ════════════════════════════════════════════════════════════════════════

    // ── Power domains ───────────────────────────────────────────────────
    // main: Switchable main domain — CPU, memory, peripherals
    // aon (always-on): Always-on domain — wakeup logic, timers (future)

    // ── Clock and reset ─────────────────────────────────────────────────
    // clk_sys: 40 MHz (port: clk_i)
    output wire        clk_o,
    output wire        rst_no,

    // ── Peripheral I/O ──────────────────────────────────────────────────
    output wire        uart_rx_o,    // u_uart.cio_rx_i (input from external)
    input  wire        uart_tx_i,    // u_uart.cio_tx_o (output to external)
    input  wire        spi_sclk_i,    // u_spi_host.spi_sclk_o (output to external)
    input  wire        spi_cs_n_i,    // u_spi_host.spi_cs_no (output to external)
    input  wire        spi_mosi_i,    // u_spi_host.spi_mosi_o (output to external)
    output wire        spi_miso_o,    // u_spi_host.spi_miso_i (input from external)
    input  wire        fft_done_i,    // u_fft.fft_done_o (output to external)
    output wire        jtag_tck_o,    // u_dm.tck (input from external)
    output wire        jtag_tms_o,    // u_dm.tms (input from external)
    output wire        jtag_tdi_o,    // u_dm.tdi (input from external)
    output wire        jtag_trst_n_o,    // u_dm.trst_n (input from external)
    input  wire        jtag_tdo_i,    // u_dm.tdo (output to external)

    // ── Interrupts ──────────────────────────────────────────────────────
    input  wire        plic_irq_i,            // aggregate PLIC output
    input  wire        intr_uart_tx_watermark_i,   // [1] u_uart.intr_tx_watermark_o
    input  wire        intr_uart_tx_empty_i,   // [2] u_uart.intr_tx_empty_o
    input  wire        intr_uart_rx_watermark_i,   // [3] u_uart.intr_rx_watermark_o
    input  wire        intr_uart_tx_done_i,   // [4] u_uart.intr_tx_done_o
    input  wire        intr_uart_rx_overflow_i,   // [5] u_uart.intr_rx_overflow_o
    input  wire        intr_uart_rx_frame_err_i,   // [6] u_uart.intr_rx_frame_err_o
    input  wire        intr_uart_rx_break_err_i,   // [7] u_uart.intr_rx_break_err_o
    input  wire        intr_uart_rx_timeout_i,   // [8] u_uart.intr_rx_timeout_o
    input  wire        intr_uart_rx_parity_err_i,   // [9] u_uart.intr_rx_parity_err_o
    input  wire        intr_spi_host_tx_empty_i,   // [10] u_spi_host.intr_tx_empty_o
    input  wire        intr_spi_host_rx_full_i,   // [11] u_spi_host.intr_rx_full_o
    input  wire        intr_spi_host_idle_i,   // [12] u_spi_host.intr_idle_o
    // fft_done_i already declared as GPIO port  // [13] u_fft.fft_done_o
    input  wire        fft_error_i,   // [14] u_fft.fft_error_o
    output wire [31:0] intr_vec_o             // assembled interrupt vector

    // ── Debug / DFT (from lifecycle) ────────────────────────────────────
    // States: manufacturing (debug) (DFT), development (debug), production, rma (debug) (DFT)

);

    // ════════════════════════════════════════════════════════════════════
    // Target Adapter: Caravel I/O
    // ════════════════════════════════════════════════════════════════════
    // ════════════════════════════════════════════════════════════════════════
    // Caravel Adapter
    // Maps SoC interface to Caravel io_in/io_out/io_oeb + tie-offs
    // ════════════════════════════════════════════════════════════════════════

    // ── Clock / reset mapping ───────────────────────────────────────────
    assign clk_o  = wb_clk_i;
    assign rst_no = ~wb_rst_i;

    // ── Wishbone tie-offs (SoC does not use Caravel Wishbone bus) ───────
    assign wbs_ack_o   = 1'b0;
    assign wbs_dat_o   = 32'h0;

    // ── Logic analyzer tie-offs ─────────────────────────────────────────
    assign la_data_out = 128'h0;

    // ── GPIO input routing (io_in → SoC interface) ──────────────────────
    assign uart_rx_o = io_in[0];  // uart_rx
    assign spi_miso_o = io_in[5];  // spi_miso
    assign jtag_tck_o = io_in[7];  // jtag_tck
    assign jtag_tms_o = io_in[8];  // jtag_tms
    assign jtag_tdi_o = io_in[9];  // jtag_tdi
    assign jtag_trst_n_o = io_in[11];  // jtag_trst_n

    // ── GPIO output routing (SoC interface → io_out) ────────────────────
    assign io_out[0] = 1'b0;
    assign io_out[1] = uart_tx_i;  // uart_tx
    assign io_out[2] = spi_sclk_i;  // spi_sclk
    assign io_out[3] = spi_cs_n_i;  // spi_cs_n
    assign io_out[4] = spi_mosi_i;  // spi_mosi
    assign io_out[5] = 1'b0;
    assign io_out[6] = fft_done_i;  // fft_done
    assign io_out[7] = 1'b0;
    assign io_out[8] = 1'b0;
    assign io_out[9] = 1'b0;
    assign io_out[10] = jtag_tdo_i;  // jtag_tdo
    assign io_out[11] = 1'b0;
    assign io_out[12] = 1'b0;
    assign io_out[13] = 1'b0;
    assign io_out[14] = 1'b0;
    assign io_out[15] = 1'b0;
    assign io_out[16] = 1'b0;
    assign io_out[17] = 1'b0;
    assign io_out[18] = 1'b0;
    assign io_out[19] = 1'b0;
    assign io_out[20] = 1'b0;
    assign io_out[21] = 1'b0;
    assign io_out[22] = 1'b0;
    assign io_out[23] = 1'b0;
    assign io_out[24] = 1'b0;
    assign io_out[25] = 1'b0;
    assign io_out[26] = 1'b0;
    assign io_out[27] = 1'b0;
    assign io_out[28] = 1'b0;
    assign io_out[29] = 1'b0;
    assign io_out[30] = 1'b0;
    assign io_out[31] = 1'b0;
    assign io_out[32] = 1'b0;
    assign io_out[33] = 1'b0;
    assign io_out[34] = 1'b0;
    assign io_out[35] = 1'b0;
    assign io_out[36] = 1'b0;
    assign io_out[37] = 1'b0;

    // ── GPIO output enable (0=output, 1=input) ─────────────────────────
    assign io_oeb[0] = 1'b1;  // input
    assign io_oeb[1] = 1'b0;  // output
    assign io_oeb[2] = 1'b0;  // output
    assign io_oeb[3] = 1'b0;  // output
    assign io_oeb[4] = 1'b0;  // output
    assign io_oeb[5] = 1'b1;  // input
    assign io_oeb[6] = 1'b0;  // output
    assign io_oeb[7] = 1'b1;  // input
    assign io_oeb[8] = 1'b1;  // input
    assign io_oeb[9] = 1'b1;  // input
    assign io_oeb[10] = 1'b0;  // output
    assign io_oeb[11] = 1'b1;  // input
    assign io_oeb[12] = 1'b1;  // input
    assign io_oeb[13] = 1'b1;  // input
    assign io_oeb[14] = 1'b1;  // input
    assign io_oeb[15] = 1'b1;  // input
    assign io_oeb[16] = 1'b1;  // input
    assign io_oeb[17] = 1'b1;  // input
    assign io_oeb[18] = 1'b1;  // input
    assign io_oeb[19] = 1'b1;  // input
    assign io_oeb[20] = 1'b1;  // input
    assign io_oeb[21] = 1'b1;  // input
    assign io_oeb[22] = 1'b1;  // input
    assign io_oeb[23] = 1'b1;  // input
    assign io_oeb[24] = 1'b1;  // input
    assign io_oeb[25] = 1'b1;  // input
    assign io_oeb[26] = 1'b1;  // input
    assign io_oeb[27] = 1'b1;  // input
    assign io_oeb[28] = 1'b1;  // input
    assign io_oeb[29] = 1'b1;  // input
    assign io_oeb[30] = 1'b1;  // input
    assign io_oeb[31] = 1'b1;  // input
    assign io_oeb[32] = 1'b1;  // input
    assign io_oeb[33] = 1'b1;  // input
    assign io_oeb[34] = 1'b1;  // input
    assign io_oeb[35] = 1'b1;  // input
    assign io_oeb[36] = 1'b1;  // input
    assign io_oeb[37] = 1'b1;  // input

    // ── IRQ to Caravel management SoC ───────────────────────────────────
    assign user_irq = {2'b0, plic_irq_i};

    // ── Interrupt vector assembly ───────────────────────────────────────
    assign intr_vec_o = {
        1'b0,  // 31: unused
        1'b0,  // 30: unused
        1'b0,  // 29: unused
        1'b0,  // 28: unused
        1'b0,  // 27: unused
        1'b0,  // 26: unused
        1'b0,  // 25: unused
        1'b0,  // 24: unused
        1'b0,  // 23: unused
        1'b0,  // 22: unused
        1'b0,  // 21: unused
        1'b0,  // 20: unused
        1'b0,  // 19: unused
        1'b0,  // 18: unused
        1'b0,  // 17: unused
        1'b0,  // 16: unused
        1'b0,  // 15: unused
        fft_error_i,  // 14: u_fft.fft_error_o
        fft_done_i,  // 13: u_fft.fft_done_o
        intr_spi_host_idle_i,  // 12: u_spi_host.intr_idle_o
        intr_spi_host_rx_full_i,  // 11: u_spi_host.intr_rx_full_o
        intr_spi_host_tx_empty_i,  // 10: u_spi_host.intr_tx_empty_o
        intr_uart_rx_parity_err_i,  // 9: u_uart.intr_rx_parity_err_o
        intr_uart_rx_timeout_i,  // 8: u_uart.intr_rx_timeout_o
        intr_uart_rx_break_err_i,  // 7: u_uart.intr_rx_break_err_o
        intr_uart_rx_frame_err_i,  // 6: u_uart.intr_rx_frame_err_o
        intr_uart_rx_overflow_i,  // 5: u_uart.intr_rx_overflow_o
        intr_uart_tx_done_i,  // 4: u_uart.intr_tx_done_o
        intr_uart_rx_watermark_i,  // 3: u_uart.intr_rx_watermark_o
        intr_uart_tx_empty_i,  // 2: u_uart.intr_tx_empty_o
        intr_uart_tx_watermark_i,  // 1: u_uart.intr_tx_watermark_o
        1'b0  // 0: unused
    };

endmodule

`default_nettype wire