// Caravel user_project_wrapper — Pure structural integration shell
// Generated by vyges-soc-generator for edge_sensor
//
// ZERO assigns (except ROM/RAM stubs), ZERO logic at this level.
// All integration logic (reset, tie-offs, GPIO) inside edge_sensor_glue.
// Pattern: mole99/caravel_wfg_sky130, dineshannayya/riscduino
//
// GPIO + interrupt wires + glue port connections are driven by soc-spec.yaml
// (caravel.gpio[] + connectivity.interrupts.mapping[]) via gpio_pins and
// interrupt_pins iteration — stays in sync with edge_sensor_glue.

`default_nettype none

module user_project_wrapper #(
    parameter BITS = 32
) (
`ifdef USE_POWER_PINS
    inout vdda1,
    inout vdda2,
    inout vssa1,
    inout vssa2,
    inout vccd1,
    inout vccd2,
    inout vssd1,
    inout vssd2,
`endif
    input  wb_clk_i,
    input  wb_rst_i,
    input  wbs_stb_i,
    input  wbs_cyc_i,
    input  wbs_we_i,
    input  [3:0]  wbs_sel_i,
    input  [31:0] wbs_dat_i,
    input  [31:0] wbs_adr_i,
    output wbs_ack_o,
    output [31:0] wbs_dat_o,
    input  [127:0] la_data_in,
    output [127:0] la_data_out,
    input  [127:0] la_oenb,
    input  [`MPRJ_IO_PADS-1:0] io_in,
    output [`MPRJ_IO_PADS-1:0] io_out,
    output [`MPRJ_IO_PADS-1:0] io_oeb,
    inout  [`MPRJ_IO_PADS-10:0] analog_io,
    input  user_clock2,
    output [2:0] user_irq
);

    // ── Internal wires ──────────────────────────────────────────────────────
    wire clk;
    wire rst_n;

    // TL-UL buses (110-bit H2D, 66-bit D2H)
    wire [109:0] tl_cpu_h2d, tl_uart_h2d, tl_spi_h2d, tl_plic_h2d, tl_fft_h2d;
    wire [109:0] tl_rom_h2d, tl_ram_h2d;
    wire [65:0]  tl_cpu_d2h, tl_uart_d2h, tl_spi_d2h, tl_plic_d2h, tl_fft_d2h;
    wire [65:0]  tl_rom_d2h, tl_ram_d2h;

    // Peripheral signals (from soc-spec caravel.gpio[])
    wire uart_rx;  // pin 0 input — u_uart.cio_rx_i
    wire uart_tx;  // pin 1 output — u_uart.cio_tx_o
    wire spi_sclk;  // pin 2 output — u_spi_host.spi_sclk_o
    wire spi_cs_n;  // pin 3 output — u_spi_host.spi_cs_no
    wire spi_mosi;  // pin 4 output — u_spi_host.spi_mosi_o
    wire spi_miso;  // pin 5 input — u_spi_host.spi_miso_i
    wire fft_done;  // pin 6 output — u_fft.fft_done_o

    // Interrupt wires (from soc-spec connectivity.interrupts.mapping[])
    wire plic_irq;
    wire [31:0] intr_vec;
    wire intr_uart_tx_watermark;  // PLIC [1] u_uart.intr_tx_watermark_o
    wire intr_uart_tx_empty;  // PLIC [2] u_uart.intr_tx_empty_o
    wire intr_uart_rx_watermark;  // PLIC [3] u_uart.intr_rx_watermark_o
    wire intr_uart_tx_done;  // PLIC [4] u_uart.intr_tx_done_o
    wire intr_uart_rx_overflow;  // PLIC [5] u_uart.intr_rx_overflow_o
    wire intr_uart_rx_frame_err;  // PLIC [6] u_uart.intr_rx_frame_err_o
    wire intr_uart_rx_break_err;  // PLIC [7] u_uart.intr_rx_break_err_o
    wire intr_uart_rx_timeout;  // PLIC [8] u_uart.intr_rx_timeout_o
    wire intr_uart_rx_parity_err;  // PLIC [9] u_uart.intr_rx_parity_err_o
    wire intr_spi_host_tx_empty;  // PLIC [10] u_spi_host.intr_tx_empty_o
    wire intr_spi_host_rx_full;  // PLIC [11] u_spi_host.intr_rx_full_o
    wire intr_spi_host_idle;  // PLIC [12] u_spi_host.intr_idle_o
    wire fft_error;  // PLIC [14] u_fft.fft_error_o

    // ── Glue macro ──────────────────────────────────────────────────────────
    edge_sensor_glue u_glue (
        .wb_clk_i       (wb_clk_i),
        .wb_rst_i       (wb_rst_i),
        .wbs_stb_i      (wbs_stb_i),
        .wbs_cyc_i      (wbs_cyc_i),
        .wbs_we_i       (wbs_we_i),
        .wbs_sel_i      (wbs_sel_i),
        .wbs_dat_i      (wbs_dat_i),
        .wbs_adr_i      (wbs_adr_i),
        .wbs_ack_o      (wbs_ack_o),
        .wbs_dat_o      (wbs_dat_o),
        .la_data_in     (la_data_in),
        .la_data_out    (la_data_out),
        .la_oenb        (la_oenb),
        .io_in          (io_in),
        .io_out         (io_out),
        .io_oeb         (io_oeb),
        .user_irq       (user_irq),
        .clk_o          (clk),
        .rst_no         (rst_n),
        .uart_rx_o     (uart_rx),
        .uart_tx_i     (uart_tx),
        .spi_sclk_i     (spi_sclk),
        .spi_cs_n_i     (spi_cs_n),
        .spi_mosi_i     (spi_mosi),
        .spi_miso_o     (spi_miso),
        .fft_done_i     (fft_done),
        .plic_irq_i     (plic_irq),
        .intr_uart_tx_watermark_i    (intr_uart_tx_watermark),
        .intr_uart_tx_empty_i    (intr_uart_tx_empty),
        .intr_uart_rx_watermark_i    (intr_uart_rx_watermark),
        .intr_uart_tx_done_i    (intr_uart_tx_done),
        .intr_uart_rx_overflow_i    (intr_uart_rx_overflow),
        .intr_uart_rx_frame_err_i    (intr_uart_rx_frame_err),
        .intr_uart_rx_break_err_i    (intr_uart_rx_break_err),
        .intr_uart_rx_timeout_i    (intr_uart_rx_timeout),
        .intr_uart_rx_parity_err_i    (intr_uart_rx_parity_err),
        .intr_spi_host_tx_empty_i    (intr_spi_host_tx_empty),
        .intr_spi_host_rx_full_i    (intr_spi_host_rx_full),
        .intr_spi_host_idle_i    (intr_spi_host_idle),
        .fft_error_i    (fft_error),
        .intr_vec_o     (intr_vec)
    );

    // ── Crossbar ────────────────────────────────────────────────────────────
    // Host port is named tl_host_i/o on xbar_main (single-host naming).
    // FFT is architecturally behind the APB sub-bus (tl_u_xbar_apb_o ->
    // tlul_apb_adapter -> apb_sub_bus_apb -> fft APB slave); the adapter
    // and sub-bus are not instantiated at this wrapper scope, so tl_xbar_apb
    // is tied off here -- CPU accesses into the FFT address range simply
    // never complete. Wire up the adapter + sub-bus to enable FFT.
    wire [109:0] tl_xbar_apb_h2d;
    wire [65:0]  tl_xbar_apb_d2h;
    assign tl_xbar_apb_d2h = 66'h0;
    xbar_main u_xbar (
        .clk_i            (clk),
        .rst_ni           (rst_n),
        .tl_host_i        (tl_cpu_h2d),
        .tl_host_o        (tl_cpu_d2h),
        .tl_u_uart_o      (tl_uart_h2d),
        .tl_u_uart_i      (tl_uart_d2h),
        .tl_u_spi_host_o  (tl_spi_h2d),
        .tl_u_spi_host_i  (tl_spi_d2h),
        .tl_u_plic_o      (tl_plic_h2d),
        .tl_u_plic_i      (tl_plic_d2h),
        .tl_u_rom_o       (tl_rom_h2d),
        .tl_u_rom_i       (tl_rom_d2h),
        .tl_u_ram_o       (tl_ram_h2d),
        .tl_u_ram_i       (tl_ram_d2h),
        .tl_u_xbar_apb_o  (tl_xbar_apb_h2d),
        .tl_u_xbar_apb_i  (tl_xbar_apb_d2h)    );

    // =========================================================================
    // P3 DESIGN NOTE — metadata-driven instance bindings (not yet implemented)
    // =========================================================================
    // Today the per-IP port lists below (CPU, UART, SPI, PLIC, FFT, DM) are
    // hand-authored against a specific snapshot of each IP's port contract.
    // When any IP renames or adds a port (e.g. xbar rename
    // tl_u_ibex -> tl_host), the wrapper silently breaks at harden time.
    //
    // Target design: iterate each macro's vyges-metadata.json
    // `interfaces[]` block, resolve the port name + direction per signal,
    // and emit .port_name(wire_name) bindings from that source-of-truth.
    // Shape:
    //
    //   for iface in macro.interfaces:
    //       for sig in iface.signals:
    //           emit: .{sig.name}({resolve_wire_from_connectivity(iface, sig, instance)})
    //
    // Wire-name resolution draws from soc.connectivity (bus, interrupt,
    // gpio, debug_req) + soc.caravel.gpio[] pin mappings. Tieoffs
    // (alert_rx_i, racl_policies_i, etc.) use the existing
    // wiring_generator._wire_tieoff default-0 rule. IO signals use
    // _wire_io's top-level port-name convention.
    //
    // Effort: ~1.5 days including per-IP contract sign-off (UART, SPI, PLIC,
    // FFT, DM, raw fft_top, rv_core_ibex_tlul) + regression across
    // edge_sensor, edge_sensor_dsp, multi-core.
    // Cross-ref: soc-generator/docs/metadata-driven-wrapper.md (TBD).
    // Tracked in deckrun-server/docs/todo.md floorplan section.
    // =========================================================================

    // ── CPU ─────────────────────────────────────────────────────────────────
    // debug_req_i is not exposed on the hardened rv_core_ibex_tlul gate-level
    // netlist (DbgTriggerEn=0 during synth drops the port). Debug halt is
    // reached via the DM's slave interface + JTAG only; CPU-side
    // debug-trigger integration requires re-hardening with DbgTriggerEn=1.
    rv_core_ibex_tlul u_ibex (
        .clk_i          (clk),
        .rst_ni         (rst_n),
        .boot_addr_i    (32'h00008000),
        .hart_id_i      (32'h0),
        .tl_o           (tl_cpu_h2d),
        .tl_i           (tl_cpu_d2h),
        .irq_software_i (1'b0),
        .irq_timer_i    (1'b0),
        .irq_external_i (plic_irq),
        .core_sleep_o   ()
    );

    // ── UART ────────────────────────────────────────────────────────────────
    uart u_uart (
        .clk_i                  (clk),
        .rst_ni                 (rst_n),
        .tl_i                   (tl_uart_h2d),
        .tl_o                   (tl_uart_d2h),
        .cio_rx_i               (uart_rx),
        .cio_tx_o               (uart_tx),
        .cio_tx_en_o            (),
        .intr_tx_watermark_o    (intr_uart_tx_watermark),
        .intr_rx_watermark_o    (intr_uart_rx_watermark),
        .intr_tx_done_o         (intr_uart_tx_done),
        .intr_rx_overflow_o     (intr_uart_rx_overflow),
        .intr_rx_frame_err_o    (intr_uart_rx_frame_err),
        .intr_rx_break_err_o    (intr_uart_rx_break_err),
        .intr_rx_timeout_o      (intr_uart_rx_timeout),
        .intr_rx_parity_err_o   (intr_uart_rx_parity_err),
        .intr_tx_empty_o        (intr_uart_tx_empty),
        .lsio_trigger_o         (),
        .alert_rx_i             (4'b0),
        .alert_tx_o             (),
        .racl_policies_i        (8'b0),
        .racl_error_o           ()
    );

    // ── SPI Host ────────────────────────────────────────────────────────────
    spi_host_lite u_spi_host (
        .clk_i          (clk),
        .rst_ni         (rst_n),
        .tl_i           (tl_spi_h2d),
        .tl_o           (tl_spi_d2h),
        .spi_sclk_o     (spi_sclk),
        .spi_cs_no      (spi_cs_n),
        .spi_mosi_o     (spi_mosi),
        .spi_miso_i     (spi_miso),
        .intr_tx_empty_o(intr_spi_host_tx_empty),
        .intr_rx_full_o (intr_spi_host_rx_full),
        .intr_idle_o    (intr_spi_host_idle)
    );

    // ── PLIC ────────────────────────────────────────────────────────────────
    rv_plic_lite u_plic (
        .clk_i          (clk),
        .rst_ni         (rst_n),
        .tl_i           (tl_plic_h2d),
        .tl_o           (tl_plic_d2h),
        .intr_src_i     (intr_vec),
        .irq_o          (plic_irq)
    );

    // ── FFT Accelerator (TL-UL-wrapped; APB sub-bus tied off) ───────────────
    // Simpler variant: fft_ctrl_tlul includes tlul_apb_adapter internally,
    // expects a direct TL-UL slave wire from xbar_main. Current xbar has
    // no tl_u_fft slave port, so FFT is instantiated for GDS completeness
    // but its TL-UL port is tied off -- CPU cannot reach it. Enable spec's
    // apb_sub_bus.enable=true for the full APB-routed variant above.
    wire [65:0] fft_tl_o_unused;
    fft_ctrl_tlul u_fft (
        .clk_i          (clk),
        .rst_ni         (rst_n),
        .tl_i           (110'h0),
        .tl_o           (fft_tl_o_unused),
        .fft_done_o     (fft_done),
        .fft_error_o    (fft_error)
    );

    // ── ROM / RAM stubs ─────────────────────────────────────────────────────
    assign tl_rom_d2h = 66'h0;
    assign tl_ram_d2h = 66'h0;

endmodule

`default_nettype wire