// Caravel user_project_wrapper — Pure structural integration shell
// Generated by vyges-soc-generator for edge_sensor
//
// ZERO assigns (except ROM/RAM stubs), ZERO logic at this level.
// All integration logic (reset, tie-offs, GPIO) inside edge_sensor_glue.
// Pattern: mole99/caravel_wfg_sky130, dineshannayya/riscduino
//
// GPIO + interrupt wires + glue port connections are driven by soc-spec.yaml
// (caravel.gpio[] + connectivity.interrupts.mapping[]) via gpio_pins and
// interrupt_pins iteration — stays in sync with edge_sensor_glue.

`default_nettype none

module user_project_wrapper #(
    parameter BITS = 32
) (
`ifdef USE_POWER_PINS
    inout vdda1,
    inout vdda2,
    inout vssa1,
    inout vssa2,
    inout vccd1,
    inout vccd2,
    inout vssd1,
    inout vssd2,
`endif
    input  wb_clk_i,
    input  wb_rst_i,
    input  wbs_stb_i,
    input  wbs_cyc_i,
    input  wbs_we_i,
    input  [3:0]  wbs_sel_i,
    input  [31:0] wbs_dat_i,
    input  [31:0] wbs_adr_i,
    output wbs_ack_o,
    output [31:0] wbs_dat_o,
    input  [127:0] la_data_in,
    output [127:0] la_data_out,
    input  [127:0] la_oenb,
    input  [`MPRJ_IO_PADS-1:0] io_in,
    output [`MPRJ_IO_PADS-1:0] io_out,
    output [`MPRJ_IO_PADS-1:0] io_oeb,
    inout  [`MPRJ_IO_PADS-10:0] analog_io,
    input  user_clock2,
    output [2:0] user_irq
);

    // ── Internal wires ──────────────────────────────────────────────────────
    wire clk;
    wire rst_n;

    // TL-UL buses (110-bit H2D, 66-bit D2H)
    wire [109:0] tl_cpu_h2d, tl_uart_h2d, tl_spi_h2d, tl_plic_h2d, tl_fft_h2d;
    wire [109:0] tl_rom_h2d, tl_ram_h2d;
    wire [65:0]  tl_cpu_d2h, tl_uart_d2h, tl_spi_d2h, tl_plic_d2h, tl_fft_d2h;
    wire [65:0]  tl_rom_d2h, tl_ram_d2h;

    // Peripheral signals (from soc-spec caravel.gpio[])
    wire uart_rx;  // pin 0 input — u_uart.cio_rx_i
    wire uart_tx;  // pin 1 output — u_uart.cio_tx_o
    wire spi_sclk;  // pin 2 output — u_spi_host.spi_sclk_o
    wire spi_cs_n;  // pin 3 output — u_spi_host.spi_cs_no
    wire spi_mosi;  // pin 4 output — u_spi_host.spi_mosi_o
    wire spi_miso;  // pin 5 input — u_spi_host.spi_miso_i
    wire fft_done;  // pin 6 output — u_fft.fft_done_o
    wire jtag_tck;  // pin 7 input — u_dm.tck
    wire jtag_tms;  // pin 8 input — u_dm.tms
    wire jtag_tdi;  // pin 9 input — u_dm.tdi
    wire jtag_trst_n;  // pin 11 input — u_dm.trst_n
    wire jtag_tdo;  // pin 10 output — u_dm.tdo

    // Interrupt wires (from soc-spec connectivity.interrupts.mapping[])
    wire plic_irq;
    wire [31:0] intr_vec;
    wire intr_uart_tx_watermark;  // PLIC [1] u_uart.intr_tx_watermark_o
    wire intr_uart_tx_empty;  // PLIC [2] u_uart.intr_tx_empty_o
    wire intr_uart_rx_watermark;  // PLIC [3] u_uart.intr_rx_watermark_o
    wire intr_uart_tx_done;  // PLIC [4] u_uart.intr_tx_done_o
    wire intr_uart_rx_overflow;  // PLIC [5] u_uart.intr_rx_overflow_o
    wire intr_uart_rx_frame_err;  // PLIC [6] u_uart.intr_rx_frame_err_o
    wire intr_uart_rx_break_err;  // PLIC [7] u_uart.intr_rx_break_err_o
    wire intr_uart_rx_timeout;  // PLIC [8] u_uart.intr_rx_timeout_o
    wire intr_uart_rx_parity_err;  // PLIC [9] u_uart.intr_rx_parity_err_o
    wire intr_spi_host_tx_empty;  // PLIC [10] u_spi_host.intr_tx_empty_o
    wire intr_spi_host_rx_full;  // PLIC [11] u_spi_host.intr_rx_full_o
    wire intr_spi_host_idle;  // PLIC [12] u_spi_host.intr_idle_o
    wire fft_error;  // PLIC [14] u_fft.fft_error_o

    // ── Glue macro ──────────────────────────────────────────────────────────
    edge_sensor_glue u_glue (
        .wb_clk_i       (wb_clk_i),
        .wb_rst_i       (wb_rst_i),
        .wbs_stb_i      (wbs_stb_i),
        .wbs_cyc_i      (wbs_cyc_i),
        .wbs_we_i       (wbs_we_i),
        .wbs_sel_i      (wbs_sel_i),
        .wbs_dat_i      (wbs_dat_i),
        .wbs_adr_i      (wbs_adr_i),
        .wbs_ack_o      (wbs_ack_o),
        .wbs_dat_o      (wbs_dat_o),
        .la_data_in     (la_data_in),
        .la_data_out    (la_data_out),
        .la_oenb        (la_oenb),
        .io_in          (io_in),
        .io_out         (io_out),
        .io_oeb         (io_oeb),
        .user_irq       (user_irq),
        .clk_o          (clk),
        .rst_no         (rst_n),
        .uart_rx_o     (uart_rx),
        .uart_tx_i     (uart_tx),
        .spi_sclk_i     (spi_sclk),
        .spi_cs_n_i     (spi_cs_n),
        .spi_mosi_i     (spi_mosi),
        .spi_miso_o     (spi_miso),
        .fft_done_i     (fft_done),
        .jtag_tck_o     (jtag_tck),
        .jtag_tms_o     (jtag_tms),
        .jtag_tdi_o     (jtag_tdi),
        .jtag_trst_n_o     (jtag_trst_n),
        .jtag_tdo_i     (jtag_tdo),
        .plic_irq_i     (plic_irq),
        .intr_uart_tx_watermark_i    (intr_uart_tx_watermark),
        .intr_uart_tx_empty_i    (intr_uart_tx_empty),
        .intr_uart_rx_watermark_i    (intr_uart_rx_watermark),
        .intr_uart_tx_done_i    (intr_uart_tx_done),
        .intr_uart_rx_overflow_i    (intr_uart_rx_overflow),
        .intr_uart_rx_frame_err_i    (intr_uart_rx_frame_err),
        .intr_uart_rx_break_err_i    (intr_uart_rx_break_err),
        .intr_uart_rx_timeout_i    (intr_uart_rx_timeout),
        .intr_uart_rx_parity_err_i    (intr_uart_rx_parity_err),
        .intr_spi_host_tx_empty_i    (intr_spi_host_tx_empty),
        .intr_spi_host_rx_full_i    (intr_spi_host_rx_full),
        .intr_spi_host_idle_i    (intr_spi_host_idle),
        .fft_error_i    (fft_error),
        .intr_vec_o     (intr_vec)
    );

    // ── Crossbar ────────────────────────────────────────────────────────────
    wire [109:0] tl_xbar_apb_h2d;
    wire [65:0]  tl_xbar_apb_d2h;
    assign tl_xbar_apb_d2h = 66'h0;  // APB sub-bus unused at this wrapper scope
    xbar_main u_xbar (
        .clk_i            (clk),
        .rst_ni           (rst_n),
        .tl_host_i        (tl_cpu_h2d),
        .tl_host_o        (tl_cpu_d2h),
        .tl_u_uart_o      (tl_uart_h2d),
        .tl_u_uart_i      (tl_uart_d2h),
        .tl_u_spi_host_o  (tl_spi_h2d),
        .tl_u_spi_host_i  (tl_spi_d2h),
        .tl_u_plic_o      (tl_plic_h2d),
        .tl_u_plic_i      (tl_plic_d2h),
        .tl_u_rom_o       (tl_rom_h2d),
        .tl_u_rom_i       (tl_rom_d2h),
        .tl_u_ram_o       (tl_ram_h2d),
        .tl_u_ram_i       (tl_ram_d2h),
        .tl_u_dm_o        (tl_u_dm_h2d),
        .tl_u_dm_i        (tl_u_dm_d2h),
        .tl_u_xbar_apb_o  (tl_xbar_apb_h2d),
        .tl_u_xbar_apb_i  (tl_xbar_apb_d2h)
    );

    // ── CPU ─────────────────────────────────────────────────────────────────
    rv_core_ibex_tlul u_ibex (
        .clk_i          (clk),
        .rst_ni         (rst_n),
        .boot_addr_i    (32'h00008000),
        .hart_id_i      (32'h0),
        .tl_o           (tl_cpu_h2d),
        .tl_i           (tl_cpu_d2h),
        .irq_software_i (1'b0),
        .irq_timer_i    (1'b0),
        .irq_external_i (plic_irq),
        .core_sleep_o   ()
    );

    // ── UART ────────────────────────────────────────────────────────────────
    uart u_uart (
        .clk_i                  (clk),
        .rst_ni                 (rst_n),
        .tl_i                   (tl_uart_h2d),
        .tl_o                   (tl_uart_d2h),
        .cio_rx_i               (uart_rx),
        .cio_tx_o               (uart_tx),
        .cio_tx_en_o            (),
        .intr_tx_watermark_o    (intr_uart_tx_watermark),
        .intr_rx_watermark_o    (intr_uart_rx_watermark),
        .intr_tx_done_o         (intr_uart_tx_done),
        .intr_rx_overflow_o     (intr_uart_rx_overflow),
        .intr_rx_frame_err_o    (intr_uart_rx_frame_err),
        .intr_rx_break_err_o    (intr_uart_rx_break_err),
        .intr_rx_timeout_o      (intr_uart_rx_timeout),
        .intr_rx_parity_err_o   (intr_uart_rx_parity_err),
        .intr_tx_empty_o        (intr_uart_tx_empty),
        .lsio_trigger_o         (),
        .alert_rx_i             (4'b0),
        .alert_tx_o             (),
        .racl_policies_i        (8'b0),
        .racl_error_o           ()
    );

    // ── SPI Host ────────────────────────────────────────────────────────────
    spi_host_lite u_spi_host (
        .clk_i          (clk),
        .rst_ni         (rst_n),
        .tl_i           (tl_spi_h2d),
        .tl_o           (tl_spi_d2h),
        .spi_sclk_o     (spi_sclk),
        .spi_cs_no      (spi_cs_n),
        .spi_mosi_o     (spi_mosi),
        .spi_miso_i     (spi_miso),
        .intr_tx_empty_o(intr_spi_host_tx_empty),
        .intr_rx_full_o (intr_spi_host_rx_full),
        .intr_idle_o    (intr_spi_host_idle)
    );

    // ── PLIC ────────────────────────────────────────────────────────────────
    rv_plic_lite u_plic (
        .clk_i          (clk),
        .rst_ni         (rst_n),
        .tl_i           (tl_plic_h2d),
        .tl_o           (tl_plic_d2h),
        .intr_src_i     (intr_vec),
        .irq_o          (plic_irq)
    );

    // ── FFT Accelerator ─────────────────────────────────────────────────────
    // NOTE: xbar_main does not route a TL-UL slave port to FFT in this build
    // (FFT is architected behind the APB sub-bus; adapter/sub-bus not yet
    // instantiated at wrapper scope). For this signoff iteration the FFT
    // macro is instantiated for GDS inclusion with its TL-UL port tied off.
    assign tl_fft_d2h = 66'h0;
    fft_ctrl_tlul u_fft (
        .clk_i          (clk),
        .rst_ni         (rst_n),
        .tl_i           (110'h0),
        .tl_o           (tl_fft_h2d_unused),
        .fft_done_o     (fft_done),
        .fft_error_o    (fft_error)
    );
    wire [65:0] tl_fft_h2d_unused;

    // ── ROM / RAM stubs ─────────────────────────────────────────────────────
    assign tl_rom_d2h = 66'h0;
    assign tl_ram_d2h = 66'h0;

    // ── Debug Module (RISC-V Debug Spec 0.13) ───────────────────────────────
    // IP: vyges-rv-dbg-tlul  (instance: u_dm)
    // Single TL-UL slave port covers an 8KB region. Inside vyges_rv_dbg_tlul,
    // pulp dm_top decodes addr[11] to route regs (0x000-0x7FF) vs mem/ROM
    // (0x800-0xFFF). SBA master tied off — phase 2c adds rv_dm as 2nd xbar
    // host for debugger-initiated memory R/W. JTAG wires are taken from the
    // gpio_pins loop above (signal names from debug_module.jtag).
    wire [109:0] tl_u_dm_h2d;
    wire [65:0]  tl_u_dm_d2h;
    wire [109:0] tl_u_dm_sba_h2d;
    wire [65:0]  tl_u_dm_sba_d2h;
    wire         u_dm_ndmreset;
    wire         u_dm_dmactive;
    wire         u_dm_debug_req;

    vyges_rv_dbg_tlul u_dm (
        .clk_i         (clk),
        .rst_ni        (rst_n),
        .next_dm_addr_i(32'h0),
        .testmode_i    (1'b0),
        .ndmreset_o    (u_dm_ndmreset),
        .ndmreset_ack_i(1'b1),
        .dmactive_o    (u_dm_dmactive),
        .debug_req_o   (u_dm_debug_req),
        .unavailable_i (1'b0),
        .regs_tl_d_i   (tl_u_dm_h2d),
        .regs_tl_d_o   (tl_u_dm_d2h),
        .sba_tl_h_o    (tl_u_dm_sba_h2d),
        .sba_tl_h_i    (tl_u_dm_sba_d2h),
        .jtag_tck_i    (jtag_tck),
        .jtag_tms_i    (jtag_tms),
        .jtag_tdi_i    (jtag_tdi),
        .jtag_tdo_o    (jtag_tdo),
        .jtag_tdo_oe_o (),
        .jtag_trst_ni  (jtag_trst_n)
    );
    // SBA master response tied off (Phase 2c adds rv_dm as 2nd xbar host)
    assign tl_u_dm_sba_d2h   = 66'h0;

endmodule

`default_nettype wire