/* Auto-generated by Vyges SoC Generator — 2026-04-03T15:21:44Z */
/* Source: soc-spec.yaml -> firmware/edge_sensor.h */
/* DO NOT EDIT — regenerate with: soc-generator generate soc-spec.yaml */

#ifndef EDGE_SENSOR_H
#define EDGE_SENSOR_H

#include <stdint.h>

/* ── Memory ────────────────────────────────────────────── */
#define ROM_BASE          0x00008000U
#define ROM_SIZE          0x00008000U  /* 32 KB */
#define RAM_BASE          0x10000000U
#define RAM_SIZE          0x00020000U  /* 128 KB */
#define STACK_TOP            (RAM_BASE + RAM_SIZE)

/* ── Peripherals ───────────────────────────────────────── */
#define U_UART_BASE  0x40000000U
#define U_UART_SIZE  0x00001000U  /* 4 KB */
#define U_SPI_HOST_BASE  0x40200000U
#define U_SPI_HOST_SIZE  0x00001000U  /* 4 KB */
#define U_PLIC_BASE  0x40300000U
#define U_PLIC_SIZE  0x00001000U  /* 4 KB */
#define U_FFT_BASE  0x40100000U
#define U_FFT_SIZE  0x00001000U  /* 4 KB */

/* ── Clock ─────────────────────────────────────────────── */
#define CLK_FREQ_HZ          50000000U  /* 50 MHz */

/* ── Power domains ─────────────────────────────────────── */
#define PD_MAIN            0U
#define PD_MAIN_ALWAYS_ON  0
#define PD_AON            1U
#define PD_AON_ALWAYS_ON  1

/* ── Interrupts (PLIC source IDs) ─────────────────────── */
#define PLIC_BASE            0x40300000U
#define IRQ_UART_TX_WATERMARK  1
#define IRQ_UART_TX_EMPTY  2
#define IRQ_UART_RX_WATERMARK  3
#define IRQ_UART_TX_DONE  4
#define IRQ_UART_RX_OVERFLOW  5
#define IRQ_UART_RX_FRAME_ERR  6
#define IRQ_UART_RX_BREAK_ERR  7
#define IRQ_UART_RX_TIMEOUT  8
#define IRQ_UART_RX_PARITY_ERR  9
#define IRQ_SPI_HOST_TX_EMPTY  10
#define IRQ_SPI_HOST_RX_FULL  11
#define IRQ_SPI_HOST_IDLE  12
#define IRQ_FFT_FFT_DONE  13
#define IRQ_FFT_FFT_ERROR  14

/* ── Lifecycle states ──────────────────────────────────── */
#define LC_MANUFACTURING            0U
#define LC_MANUFACTURING_DEBUG      1
#define LC_MANUFACTURING_DFT        1
#define LC_DEVELOPMENT            1U
#define LC_DEVELOPMENT_DEBUG      1
#define LC_DEVELOPMENT_DFT        0
#define LC_PRODUCTION            2U
#define LC_PRODUCTION_DEBUG      0
#define LC_PRODUCTION_DFT        0
#define LC_RMA            3U
#define LC_RMA_DEBUG      1
#define LC_RMA_DFT        1
#define LC_NUM_STATES        4U

#endif /* EDGE_SENSOR_H */
