/* Auto-generated by Vyges SoC Generator — 2026-04-11T01:31:09Z */
/* Source: soc-spec.yaml -> firmware/edge_sensor.h */
/* DO NOT EDIT — regenerate with: soc-generator generate soc-spec.yaml */

#ifndef EDGE_SENSOR_H
#define EDGE_SENSOR_H

#include <stdint.h>

/* ── Memory ────────────────────────────────────────────── */
#define ROM_BASE          0x00008000U
#define ROM_SIZE          0x00008000U  /* 32 KB */
#define RAM_BASE          0x10000000U
#define RAM_SIZE          0x00020000U  /* 128 KB */
#define STACK_TOP            (RAM_BASE + RAM_SIZE)

/* ── Peripherals ───────────────────────────────────────── */
#define U_UART_BASE  0x40000000U
#define U_UART_SIZE  0x00001000U  /* 4 KB */
#define U_SPI_HOST_BASE  0x40200000U
#define U_SPI_HOST_SIZE  0x00001000U  /* 4 KB */
#define U_PLIC_BASE  0x40300000U
#define U_PLIC_SIZE  0x00001000U  /* 4 KB */
#define U_FFT_BASE  0x40100000U
#define U_FFT_SIZE  0x00001000U  /* 4 KB */

/* ── Clock ─────────────────────────────────────────────── */
#define CLK_FREQ_HZ          50000000U  /* 50 MHz */

/* ── Power domains ─────────────────────────────────────── */
#define PD_MAIN            0U
#define PD_MAIN_ALWAYS_ON  0
#define PD_AON            1U
#define PD_AON_ALWAYS_ON  1

/* ── Register offsets (from IP metadata) ────────────────── */
/* opentitan-uart registers */
#define U_UART_INTR_STATE  (U_UART_BASE + 0x00U)  /* RW: Interrupt state */
#define U_UART_INTR_ENABLE  (U_UART_BASE + 0x04U)  /* RW: Interrupt enable */
#define U_UART_INTR_TEST  (U_UART_BASE + 0x08U)  /* WO: Interrupt test */
#define U_UART_ALERT_TEST  (U_UART_BASE + 0x0CU)  /* WO: Alert test */
#define U_UART_CTRL  (U_UART_BASE + 0x10U)  /* RW: Control (NCO + TX/RX enable) */
#define U_UART_STATUS  (U_UART_BASE + 0x14U)  /* RO: Status (TXFULL, RXEMPTY, ...) */
#define U_UART_RDATA  (U_UART_BASE + 0x18U)  /* RO: Read data */
#define U_UART_WDATA  (U_UART_BASE + 0x1CU)  /* WO: Write data */
#define U_UART_FIFO_CTRL  (U_UART_BASE + 0x20U)  /* RW: FIFO control */
#define U_UART_FIFO_STATUS  (U_UART_BASE + 0x24U)  /* RO: FIFO status */
#define U_UART_OVRD  (U_UART_BASE + 0x28U)  /* RW: TX/RX override */
#define U_UART_VAL  (U_UART_BASE + 0x2CU)  /* RO: Sampled RX line value */
#define U_UART_TIMEOUT_CTRL  (U_UART_BASE + 0x30U)  /* RW: RX timeout control */

/* vyges-spi-host-lite registers */
#define U_SPI_HOST_CTRL  (U_SPI_HOST_BASE + 0x00U)  /* RW: enable[0], cpol[1], cpha[2], xfer_len[7:3] */
#define U_SPI_HOST_STATUS  (U_SPI_HOST_BASE + 0x04U)  /* RO: busy[0], tx_full[1], tx_empty[2], rx_full[3], rx_empty[4] */
#define U_SPI_HOST_DIV  (U_SPI_HOST_BASE + 0x08U)  /* RW: SCLK divider [15:0]  (SCLK = clk / (2*(div+1))) */
#define U_SPI_HOST_TXDATA  (U_SPI_HOST_BASE + 0x0CU)  /* WO: TX FIFO push */
#define U_SPI_HOST_RXDATA  (U_SPI_HOST_BASE + 0x10U)  /* RO: RX FIFO pop */
#define U_SPI_HOST_CSCTRL  (U_SPI_HOST_BASE + 0x14U)  /* RW: cs_assert[0]  (1=assert, 0=deassert) */
#define U_SPI_HOST_INTR_EN  (U_SPI_HOST_BASE + 0x18U)  /* RW: Interrupt enable [2:0] */
#define U_SPI_HOST_INTR_ST  (U_SPI_HOST_BASE + 0x1CU)  /* RW: Interrupt status [2:0]  (W1C) */

/* vyges-rv-plic-lite registers */
#define U_PLIC_PRIO_BASE  (U_PLIC_BASE + 0x000U)  /* RW: Priority array (32 sources, 4 bytes each) */
#define U_PLIC_PRIO_END  (U_PLIC_BASE + 0x07CU)  /* RW: Last priority slot (source 31) */
#define U_PLIC_PENDING  (U_PLIC_BASE + 0x080U)  /* RO: Pending bits [31:0] */
#define U_PLIC_ENABLE  (U_PLIC_BASE + 0x100U)  /* RW: Enable bits [31:0] */
#define U_PLIC_THRESHOLD  (U_PLIC_BASE + 0x200U)  /* RW: Priority threshold [2:0] */
#define U_PLIC_CLAIM_COMPLETE  (U_PLIC_BASE + 0x204U)  /* RW: Claim/complete (read claims, write completes) */

/* fast-fourier-transform-ip registers */
#define U_FFT_FFT_CTRL  (U_FFT_BASE + 0x0000U)  /* RW: FFT Control (start[0], done[1], ...) */
#define U_FFT_FFT_STATUS  (U_FFT_BASE + 0x0004U)  /* RO: FFT Status (busy[0], done[1], ...) */
#define U_FFT_FFT_CONFIG  (U_FFT_BASE + 0x0008U)  /* RW: FFT Configuration */
#define U_FFT_FFT_LENGTH  (U_FFT_BASE + 0x000CU)  /* RW: FFT Length (256/512/1024/2048/4096) */
#define U_FFT_BUFFER_SEL  (U_FFT_BASE + 0x0010U)  /* RW: Double-buffer select */
#define U_FFT_INT_ENABLE  (U_FFT_BASE + 0x0014U)  /* RW: Interrupt enable */
#define U_FFT_INT_STATUS  (U_FFT_BASE + 0x0018U)  /* RO: Interrupt status */
#define U_FFT_SCALE_FACTOR  (U_FFT_BASE + 0x001CU)  /* RO: Output scale factor */
#define U_FFT_RESCALE_CTRL  (U_FFT_BASE + 0x0020U)  /* RW: Rescaling control */
#define U_FFT_OVERFLOW_STATUS  (U_FFT_BASE + 0x0024U)  /* RO: Overflow status */

/* ── Interrupts (PLIC source IDs) ─────────────────────── */
#define PLIC_BASE            0x40300000U
#define IRQ_UART_TX_WATERMARK  1
#define IRQ_UART_TX_EMPTY  2
#define IRQ_UART_RX_WATERMARK  3
#define IRQ_UART_TX_DONE  4
#define IRQ_UART_RX_OVERFLOW  5
#define IRQ_UART_RX_FRAME_ERR  6
#define IRQ_UART_RX_BREAK_ERR  7
#define IRQ_UART_RX_TIMEOUT  8
#define IRQ_UART_RX_PARITY_ERR  9
#define IRQ_SPI_HOST_TX_EMPTY  10
#define IRQ_SPI_HOST_RX_FULL  11
#define IRQ_SPI_HOST_IDLE  12
#define IRQ_FFT_FFT_DONE  13
#define IRQ_FFT_FFT_ERROR  14

/* ── Lifecycle states ──────────────────────────────────── */
#define LC_MANUFACTURING            0U
#define LC_MANUFACTURING_DEBUG      1
#define LC_MANUFACTURING_DFT        1
#define LC_DEVELOPMENT            1U
#define LC_DEVELOPMENT_DEBUG      1
#define LC_DEVELOPMENT_DFT        0
#define LC_PRODUCTION            2U
#define LC_PRODUCTION_DEBUG      0
#define LC_PRODUCTION_DFT        0
#define LC_RMA            3U
#define LC_RMA_DEBUG      1
#define LC_RMA_DFT        1
#define LC_NUM_STATES        4U

#endif /* EDGE_SENSOR_H */
