// Auto-generated by Vyges SoC Generator — 2026-04-19T04:46:20Z
// DO NOT EDIT — regenerate with: soc-generator generate soc-spec.yaml

#![allow(dead_code)]

pub const ROM_BASE: u32 = 0x00008000;
pub const ROM_SIZE: u32 = 0x00008000;
pub const RAM_BASE: u32 = 0x10000000;
pub const RAM_SIZE: u32 = 0x00020000;

pub const U_UART_BASE: u32 = 0x40000000;
pub const U_UART_SIZE: u32 = 0x00001000;
pub const U_SPI_HOST_BASE: u32 = 0x40200000;
pub const U_SPI_HOST_SIZE: u32 = 0x00001000;
pub const U_PLIC_BASE: u32 = 0x40300000;
pub const U_PLIC_SIZE: u32 = 0x00001000;
pub const U_FFT_BASE: u32 = 0x40100000;
pub const U_FFT_SIZE: u32 = 0x00001000;
pub const U_DM_BASE: u32 = 0x00010000;
pub const U_DM_SIZE: u32 = 0x00002000;

pub const CLK_FREQ_HZ: u32 = 40000000;
