// @generated by vyges-soc-generator — do not hand-edit
//
// edge_sensor — boot smoke test SV wrapper
//
// Thin SystemVerilog wrapper around top_edge_sensor_sim for the cocotb
// boot smoke test. Cocotb (test_smoke.py) drives clk_i + rst_ni and reads
// dbg_pc_o to confirm CPU forward progress; this wrapper handles the parts
// cocotb cannot do directly:
//
//   1. Tying off SoC external pins that aren't relevant to the boot test
//      (UART RX held high, SPI MISO held low — no peripherals attached).
//
//   2. Loading the firmware image into the CPU's local boot ROM via a
//      hierarchical $readmemh. The rv_core_ibex_tlul module declares
//      BootRomFile = "" by default, which makes its time-0 initial fill
//      the boot ROM with NOPs. We override that array here from a
//      one-shot always-block on the first positive clock edge — runs
//      after all time-0 inits have completed but before reset deasserts,
//      so the CPU sees real firmware from its first instruction fetch.
//
//   3. Exposing the Ibex instruction-fetch PC as dbg_pc_o for cocotb to
//      sample. cocotb cannot reach into deeply-nested signals through
//      the simulator VPI without --public-flat-rw, so we surface the
//      PC as a real port on this wrapper.
//
// boot_rom.hex must exist at the path below relative to the Makefile's
// working directory at simulation time (cocotb runs the simulator from
// this test's directory, so ../../../boot_rom.hex resolves to the SoC
// repo root where the firmware Makefile drops boot_rom.hex by default).

`timescale 1ns / 1ps

module tb_smoke (
    input  wire        clk_i,
    input  wire        rst_ni,
    output wire [31:0] dbg_pc_o
);

`ifndef GLS_CARAVEL
    // ── Default mode: RTL or generic GLS ─────────────────────────────────
    // Direct instantiation of the SoC top module. Used for `make` (RTL)
    // and `make gls` (generic synthesis netlist) targets.
    wire uart_tx;
    wire spi_sclk, spi_cs_n, spi_mosi;
    wire irq_ext;

    top_edge_sensor_sim dut (
        .clk_i      (clk_i),
        .rst_ni     (rst_ni),
        .uart_tx_o  (uart_tx),
        .uart_rx_i  (1'b1),       // idle high
        .spi_sclk_o (spi_sclk),
        .spi_cs_no  (spi_cs_n),
        .spi_mosi_o (spi_mosi),
        .spi_miso_i (1'b0),       // no sensor in sim
        .irq_ext_o  (irq_ext)
    );
`else
    // ── Caravel GLS mode: instantiate user_project_wrapper ───────────────
    // For SoCs that target the Caravel chipIgnite shuttle, the hardened
    // netlist is a multi-macro user_project_wrapper rather than a flat
    // top_edge_sensor_sim. Used for the `make gls-openlane` target.
    // Hierarchical access to dut.u_ibex.boot_rom
    // still works because the wrapper directly instantiates rv_core_ibex_tlul
    // with the same instance name, and the (* keep *) attributes in the
    // source SystemVerilog tell synthesis to preserve boot_rom and
    // instr_addr through the per-macro hardening run.
    wire [37:0]  io_out, io_oeb;
    wire [127:0] la_data_out;
    wire [31:0]  wbs_dat_o;
    wire         wbs_ack_o;
    wire [2:0]   user_irq;

    user_project_wrapper dut (
        .wb_clk_i    (clk_i),
        .wb_rst_i    (~rst_ni),     // Caravel reset is active-high
        .wbs_stb_i   (1'b0),
        .wbs_cyc_i   (1'b0),
        .wbs_we_i    (1'b0),
        .wbs_sel_i   (4'b0),
        .wbs_dat_i   (32'b0),
        .wbs_adr_i   (32'b0),
        .wbs_ack_o   (wbs_ack_o),
        .wbs_dat_o   (wbs_dat_o),
        .la_data_in  (128'b0),
        .la_data_out (la_data_out),
        .la_oenb     (128'b0),
        .io_in       (38'b0),
        .io_out      (io_out),
        .io_oeb      (io_oeb),
        .analog_io   (),            // inout, leave unconnected
        .user_clock2 (clk_i),
        .user_irq    (user_irq)
    );
`endif

    // ── Surface the Ibex instruction-fetch PC for cocotb ───────────────
    assign dbg_pc_o = dut.u_ibex.instr_addr;

    // ── Boot ROM load ──────────────────────────────────────────────────
    // The rv_core_ibex_tlul declares BootRomFile = "" by default and its
    // time-0 initial fills boot_rom with NOPs. Override here
    // from an always-block on the first posedge so we run after all
    // time-0 inits and before reset deasserts.
    reg boot_rom_loaded = 1'b0;
    always @(posedge clk_i) begin
        if (!boot_rom_loaded) begin
            $readmemh("../../../boot_rom.hex", dut.u_ibex.boot_rom);
            $display("[tb_smoke] loaded boot_rom.hex; boot_rom[0]=%08h", dut.u_ibex.boot_rom[0]);
            boot_rom_loaded <= 1'b1;
        end
    end

endmodule