"""
edge_sensor — boot smoke test (cocotb)
=========================================

@generated by vyges-soc-generator — do not hand-edit

Verifies that the edge_sensor SoC boots its firmware out of the local
boot ROM and the CPU executes real firmware code (not the default-fill
NOPs that the boot ROM module uses when no firmware image is supplied).

Pass criteria:
  1. The CPU comes out of reset.
  2. The instruction-fetch PC reaches an address greater than the boot
     entry point (0x00008000) within MAX_BOOT_CYCLES.
  3. The PC continues to advance after the initial bring-up window
     (i.e. the CPU is not stuck in a single instruction).

This is a *connectivity-level* check, not a functional check. It proves
the boot path works end-to-end (boot ROM image load → reset deassert →
instruction fetch → instruction execute) without depending on any
peripheral I/O. Functional verification of individual peripherals lives
in the IP repos.

Run:
    make           # default: icarus
    make SIM=verilator
"""

import cocotb
from cocotb.clock import Clock
from cocotb.triggers import RisingEdge, ClockCycles


CLK_PERIOD_NS    = 20     # core clock period
RESET_CYCLES     = 20                        # cycles to hold reset asserted
MAX_BOOT_CYCLES  = 100_000                   # bring-up budget for the boot test
PROGRESS_CYCLES  = 5_000                     # second sample window for forward-progress check
BOOT_ENTRY_ADDR  = 0x00008000       # CPU boot_addr_i


async def _drive_reset(dut):
    """Apply reset for RESET_CYCLES, then deassert."""
    dut.rst_ni.value = 0
    await ClockCycles(dut.clk_i, RESET_CYCLES)
    dut.rst_ni.value = 1
    await RisingEdge(dut.clk_i)


@cocotb.test()
async def boot_smoke(dut):
    """edge_sensor CPU boots from boot.hex and executes real firmware."""
    # Start the system clock
    cocotb.start_soon(Clock(dut.clk_i, CLK_PERIOD_NS, units="ns").start())

    await _drive_reset(dut)
    dut._log.info("[smoke] reset released — starting boot test "
                  f"(boot_entry={BOOT_ENTRY_ADDR:#010x}, "
                  f"max_cycles={MAX_BOOT_CYCLES})")

    # ── Forward-progress check #1: PC advances past the entry point ────────
    # The boot ROM SV wrapper loads the firmware image at elaboration time
    # (via tb_smoke.sv's $readmemh into dut.u_ibex.boot_rom).
    # If the load worked, the CPU executes real instructions and PC moves
    # forward by ~1 instruction per cycle once reset deasserts.
    pc_advanced = False
    pc_initial = int(dut.dbg_pc_o.value)
    for n in range(0, MAX_BOOT_CYCLES, 1_000):
        await ClockCycles(dut.clk_i, 1_000)
        pc = int(dut.dbg_pc_o.value)
        if pc > BOOT_ENTRY_ADDR and pc != pc_initial:
            pc_advanced = True
            dut._log.info(f"[smoke] forward progress at cycle ~{n+1_000}: "
                          f"PC=0x{pc:08x}")
            break

    assert pc_advanced, (
        f"CPU PC did not advance past boot entry within {MAX_BOOT_CYCLES} "
        f"cycles. PC stuck near 0x{int(dut.dbg_pc_o.value):08x}. "
        "This usually means boot_rom.hex did not load (check tb_smoke.sv "
        "$readmemh path) or the CPU is held in reset."
    )

    # ── Forward-progress check #2: PC continues to advance ─────────────────
    # Confirms the CPU isn't stuck in a single tight loop right after entry
    # (which would indicate a bus stall, not a successful boot).
    pc_before = int(dut.dbg_pc_o.value)
    await ClockCycles(dut.clk_i, PROGRESS_CYCLES)
    pc_after = int(dut.dbg_pc_o.value)

    dut._log.info(f"[smoke] PC trace: t1=0x{pc_before:08x}  "
                  f"t2=0x{pc_after:08x}  delta={pc_after - pc_before}")

    assert pc_after != pc_before or pc_after > BOOT_ENTRY_ADDR + 0x10, (
        f"CPU PC did not advance during {PROGRESS_CYCLES}-cycle observation "
        f"window. PC=0x{pc_after:08x}. The CPU may be stuck in a tight loop "
        "(e.g. peripheral status spin-wait) or halted."
    )

    dut._log.info("[smoke] PASS — edge_sensor CPU booted from firmware "
                  "and executed real instructions")