#!/usr/bin/env bash
# © 2026 Vyges. All Rights Reserved. Generated by Vyges SoC Generator.
#
# Export a KiCad schematic to PDF + SVG + PNG with the Vyges brand
# signature, using kicad-cli headless. Runs against either the ASIC or
# FPGA variant PCBA project.
#
# Usage:
#   render_schematic.sh                          # renders pcba/asic/edge_sensor_asic.kicad_sch
#   render_schematic.sh pcba/fpga/<name>.kicad_sch
#   render_schematic.sh <input.kicad_sch> <output_dir>
#
# Requires kicad-cli 8.x or newer. Ubuntu: `sudo apt-get install kicad`.
# The PNG is signed with the Vyges brand footer; PDF and SVG are clean
# vendor outputs suitable for contest deliverables.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"

INPUT="${1:-$REPO_ROOT/pcba/asic/edge_sensor_asic.kicad_sch}"
OUTDIR="${2:-$REPO_ROOT/docs}"

if [[ ! -f "$INPUT" ]]; then
    echo "Error: schematic file not found: $INPUT" >&2
    exit 1
fi

if ! command -v kicad-cli >/dev/null 2>&1; then
    echo "Error: kicad-cli not on PATH — install KiCad 8.x+" >&2
    exit 1
fi

mkdir -p "$OUTDIR"

BASENAME="$(basename "${INPUT%.kicad_sch}")"
PDF="$OUTDIR/${BASENAME}_schematic.pdf"
SVG="$OUTDIR/${BASENAME}.svg"
PNG="$OUTDIR/${BASENAME}.png"

echo "==> PDF"
kicad-cli sch export pdf "$INPUT" -o "$PDF"

echo "==> SVG"
kicad-cli sch export svg "$INPUT" -o "$OUTDIR"

echo "==> PNG (via ImageMagick + Vyges signature)"
TMP_PNG=$(mktemp --suffix=.png)
trap 'rm -f "$TMP_PNG"' EXIT

convert -density 300 -background white -flatten "$SVG" "$TMP_PNG"
"$SCRIPT_DIR/vyges_brand_overlay.sh" "$TMP_PNG" "$PNG"

echo "Wrote: $PDF, $SVG, $PNG"