#!/usr/bin/env bash
# © 2026 Vyges. All Rights Reserved. Generated by Vyges SoC Generator.
#
# Render the mechanical enclosure SCAD to STL + PNG using OpenSCAD
# headless, then apply the Vyges brand signature. The PNG is suitable
# for README/datasheet figures; the STL is the 3D-printable mesh.
#
# Usage:
#   render_enclosure.sh              # renders pcba/asic/mechanical/enclosure.scad
#   render_enclosure.sh <input.scad> <output_dir>
#
# Requires OpenSCAD 2021.01 or newer. Ubuntu: `sudo apt-get install
# openscad xvfb`. On headless systems the render goes through
# `xvfb-run` transparently.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"

INPUT="${1:-$REPO_ROOT/pcba/asic/mechanical/enclosure.scad}"
OUTDIR="${2:-$REPO_ROOT/docs}"

if [[ ! -f "$INPUT" ]]; then
    echo "Error: SCAD file not found: $INPUT" >&2
    exit 1
fi

if ! command -v openscad >/dev/null 2>&1; then
    echo "Error: openscad not on PATH — install OpenSCAD 2021.01+" >&2
    exit 1
fi

# Detect headless environment (no DISPLAY) and wrap with xvfb-run
OPENSCAD=(openscad)
if [[ -z "${DISPLAY:-}" ]] && command -v xvfb-run >/dev/null 2>&1; then
    OPENSCAD=(xvfb-run -a openscad)
fi

mkdir -p "$OUTDIR"
BASENAME="$(basename "${INPUT%.scad}")"
SCAD_DIR="$(dirname "$INPUT")"

STL="$SCAD_DIR/${BASENAME}.stl"
TMP_PNG=$(mktemp --suffix=.png)
PNG="$OUTDIR/enclosure_render.png"

trap 'rm -f "$TMP_PNG"' EXIT

echo "==> STL"
"${OPENSCAD[@]}" -o "$STL" "$INPUT" 2>/dev/null

echo "==> PNG (raw OpenSCAD render)"
# Camera rotation 45° tilt looks down enough to read floor embossing
"${OPENSCAD[@]}" --viewall --projection=perspective \
    --camera=0,0,0,45,0,25,200 \
    --imgsize=1600,1200 --colorscheme=Tomorrow \
    -o "$TMP_PNG" "$INPUT" 2>/dev/null

echo "==> Apply Vyges signature"
"$SCRIPT_DIR/vyges_brand_overlay.sh" "$TMP_PNG" "$PNG"

echo "Wrote: $STL, $PNG"