#!/usr/bin/env bash
# © 2026 Vyges. All Rights Reserved. Generated by Vyges SoC Generator.
#
# Render a hardened GDS file to a labeled PNG using KLayout's headless
# image export, then apply the Vyges brand signature via
# vyges_brand_overlay.sh.
#
# Usage:
#   render_gds.sh                          # renders gds/edge_sensor_user_project_wrapper.gds
#   render_gds.sh gds/<macro>.gds          # render a specific macro GDS
#   render_gds.sh <input.gds> <output.png> # both explicit
#
# Requires KLayout (native or via the LibreLane docker image). Ubuntu
# package: `klayout`. Docker alternative:
#   docker run --rm -v "$(pwd)":/w -w /w ghcr.io/librelane/librelane:2.4.6 \
#       klayout -zz -r render.py
#
# The rendered PNG uses the sky130A technology layer palette and is
# cropped + signed with the Vyges footer for use in README / datasheet
# figures.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"

INPUT="${1:-$REPO_ROOT/gds/user_project_wrapper.gds}"
OUTPUT="${2:-$REPO_ROOT/docs/$(basename "${INPUT%.gds}")_layout.png}"

if [[ ! -f "$INPUT" ]]; then
    # Try gzipped variant
    if [[ -f "${INPUT}.gz" ]]; then
        echo "Decompressing ${INPUT}.gz ..."
        gunzip -k "${INPUT}.gz"
    else
        echo "Error: GDS file not found: $INPUT" >&2
        exit 1
    fi
fi

# Render script + temp PNG live under .render_tmp/ inside REPO_ROOT so
# they fall under the same docker mount as the input GDS.
RENDER_DIR="$REPO_ROOT/.render_tmp"
mkdir -p "$RENDER_DIR"
RENDER_PY="$RENDER_DIR/render_$$.py"
TMP_PNG="$RENDER_DIR/render_$$.png"
trap 'rm -rf "$RENDER_DIR"' EXIT

# Paths as seen INSIDE the design (native klayout) or the docker
# container (paths relative to /w = $REPO_ROOT).
INPUT_REL="${INPUT#$REPO_ROOT/}"
TMP_REL="${TMP_PNG#$REPO_ROOT/}"

if command -v klayout >/dev/null 2>&1; then
    SCRIPT_INPUT="$INPUT"
    SCRIPT_OUTPUT="$TMP_PNG"
else
    SCRIPT_INPUT="/w/$INPUT_REL"
    SCRIPT_OUTPUT="/w/$TMP_REL"
fi

cat > "$RENDER_PY" <<PYEOF
import pya
lv = pya.LayoutView()
lv.load_layout("$SCRIPT_INPUT", 0)
lv.max_hier_levels = 2
lv.zoom_fit()
lv.save_image("$SCRIPT_OUTPUT", 2400, 2880)
PYEOF

if command -v klayout >/dev/null 2>&1; then
    klayout -zz -r "$RENDER_PY"
elif command -v docker >/dev/null 2>&1; then
    RENDER_PY_REL="${RENDER_PY#$REPO_ROOT/}"
    docker run --rm -v "$REPO_ROOT":/w -w /w \
        ghcr.io/librelane/librelane:2.4.6 \
        klayout -zz -r "/w/$RENDER_PY_REL"
else
    echo "Error: klayout not on PATH and docker unavailable" >&2
    exit 1
fi

# Apply Vyges brand signature footer
"$SCRIPT_DIR/vyges_brand_overlay.sh" "$TMP_PNG" "$OUTPUT"
echo "Rendered GDS layout to $OUTPUT"