#!/usr/bin/env bash
# run-librelane.sh
#
# Harden edge_sensor macros via ChipFoundry LibreLane.
# Auto-generated by vyges-soc-generator — do not hand-edit.
#
# Prerequisites:
#   - cf setup --pdk sky130A  (installs PDK + LibreLane)
#   - verilog/rtl/soc_conv.v  (produced by scripts/sv2v_asic.sh)
#
# Usage:
#   bash scripts/run-librelane.sh [macro]
#   bash scripts/run-librelane.sh rv_core_ibex_tlul    # smoke test (fastest)
#   bash scripts/run-librelane.sh all          # harden all in bottom-up order
#   bash scripts/run-librelane.sh user_project_wrapper  # wrapper only (macros pre-hardened)
#
# Environment variables:
#   PDK=sky130A|sky130B       PDK variant (default: sky130A)
#
# Harden order (bottom-up):
#   1. rv_core_ibex_tlul  — CPU core (opentitan-rv-core-ibex)
#   2. uart  — Peripheral (opentitan-uart)
#   3. spi_host_lite  — Peripheral (vyges-spi-host-lite)
#   4. rv_plic_lite  — Peripheral (vyges-rv-plic-lite)
#   5. fft_ctrl_tlul  — Peripheral (fast-fourier-transform-ip)
#   6. xbar_main  — TL-UL crossbar
#   7. edge_sensor_glue  — Caravel integration glue (reset, tie-offs, GPIO)
#   8. user_project_wrapper  — final integration of all hardened macros

set -euo pipefail


REPO_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$REPO_DIR"

# ── Pre-flight check: verify all required macro configs exist ────────────────
REQUIRED_MACROS=(rv_core_ibex_tlul uart spi_host_lite rv_plic_lite fft_ctrl_tlul xbar_main edge_sensor_glue user_project_wrapper)
preflight_ok=true

for m in "${REQUIRED_MACROS[@]}"; do
  if [[ ! -f "$REPO_DIR/openlane/$m/config.json" ]]; then
    echo "ERROR: Missing OpenLane config for macro '$m' at openlane/$m/config.json" >&2
    preflight_ok=false
  fi
done
if [[ "$preflight_ok" != "true" ]]; then
  echo "ERROR: Pre-flight check failed. All ${#REQUIRED_MACROS[@]} macro configs must exist." >&2
  echo "Required: ${REQUIRED_MACROS[*]}" >&2
  exit 1
fi
echo "Pre-flight: ${#REQUIRED_MACROS[@]} macro configs verified."

MACRO="${1:-rv_core_ibex_tlul}"

PDK="${PDK:-sky130A}"

# Ensure cf CLI is available
if ! command -v cf &>/dev/null; then
  echo "ERROR: 'cf' (chipfoundry-cli) not found on PATH." >&2
  echo "  Install: pip install chipfoundry-cli" >&2
  echo "  Setup:   cf setup --pdk $PDK" >&2
  exit 1
fi

# Ensure output directories exist
mkdir -p "$REPO_DIR"/{gds,lef,lib,sdf,spef/multicorner,verilog/gl}

run_macro() {
  local m="$1"
  echo ""
  echo "=== Hardening: $m (PDK=$PDK) ==="
  local config_dir="$REPO_DIR/openlane/$m"
  if [[ ! -f "$config_dir/config.json" ]]; then
    echo "ERROR: config not found: $config_dir/config.json" >&2
    return 1
  fi

  script -qec "cf harden $m" /dev/null
  local rc=${PIPESTATUS[0]:-$?}

  if [[ $rc -ne 0 ]]; then
    echo "ERROR: cf harden $m failed with exit code $rc" >&2
    return $rc
  fi

  # Verify key outputs
  ls -la "$REPO_DIR/gds/${m}.gds" "$REPO_DIR/lef/${m}.lef" 2>/dev/null || true
  echo "=== Done: $m ==="
}

# Render the hardened wrapper GDS to a colored PNG via KLayout (non-fatal).
render_hardened_layout() {
  local script="$REPO_DIR/openlane/user_project_wrapper/render_hardened_layout.py"
  if [[ ! -f "$script" ]]; then
    return 0
  fi
  if ! command -v klayout >/dev/null 2>&1; then
    echo "  [skip] klayout not on PATH — hardened layout PNG not generated"
    return 0
  fi
  echo ""
  echo "=== Rendering hardened wrapper layout PNG ==="
  klayout -z -nc -rx -r "$script" || echo "  [warn] hardened layout render failed (non-fatal)"
}

if [[ "$MACRO" == "all" ]]; then
  run_macro rv_core_ibex_tlul
  run_macro uart
  run_macro spi_host_lite
  run_macro rv_plic_lite
  run_macro fft_ctrl_tlul
  run_macro xbar_main
  run_macro edge_sensor_glue
  run_macro user_project_wrapper
  render_hardened_layout
elif [[ "$MACRO" == "user_project_wrapper" ]]; then
  run_macro "$MACRO"
  render_hardened_layout
else
  run_macro "$MACRO"
fi