#!/usr/bin/env bash
# © 2026 Vyges. All Rights Reserved. Generated by Vyges SoC Generator.
#
# Apply the Vyges brand signature (© 2026 Vyges · Generated by Vyges SoC
# Generator) as a footer strip below any PNG. Used by render_gds.sh,
# render_schematic.sh, and render_enclosure.sh to give every
# image artifact a consistent Vyges signature.
#
# Usage:
#   vyges_brand_overlay.sh <input.png> <output.png>
#
# Requires ImageMagick (`convert`) and the Lato font (falls back to the
# first matching font family if Lato is not installed).

set -euo pipefail

INPUT="${1:-}"
OUTPUT="${2:-}"

if [[ -z "$INPUT" || -z "$OUTPUT" ]]; then
    echo "Usage: $0 <input.png> <output.png>" >&2
    exit 1
fi

if [[ ! -f "$INPUT" ]]; then
    echo "Error: input file not found: $INPUT" >&2
    exit 1
fi

FONT=""
for candidate in \
    /usr/share/fonts/truetype/lato/Lato-Medium.ttf \
    /usr/share/fonts/truetype/dejavu/DejaVuSans.ttf \
    /Library/Fonts/Lato-Medium.ttf \
    /System/Library/Fonts/Supplemental/Arial.ttf
do
    if [[ -f "$candidate" ]]; then
        FONT="$candidate"
        break
    fi
done

SIGNATURE="© 2026 Vyges. Generated by Vyges SoC Generator."

# Flatten transparency, trim excess whitespace, add margin, splice a
# 60px signature strip at the bottom, annotate, and write out.
CONVERT_FONT_ARG=()
if [[ -n "$FONT" ]]; then
    CONVERT_FONT_ARG=(-font "$FONT")
fi

convert "$INPUT" \
    -trim +repage \
    -background white -flatten \
    -bordercolor white -border 40x20 \
    -background white -splice 0x60 \
    -gravity south -pointsize 18 -fill "#444" \
    "${CONVERT_FONT_ARG[@]}" \
    -annotate +0+18 "$SIGNATURE" \
    "$OUTPUT"

echo "Wrote $OUTPUT"