// Copyright lowRISC contributors (OpenTitan project).
// Licensed under the Apache License, Version 2.0, see LICENSE for details.
// SPDX-License-Identifier: Apache-2.0
//
// *** THIS FILE IS AUTO-GENERATED BY VYGES SOC GENERATOR — DO NOT EDIT ***
//
// Generated from soc-spec.yaml soc.racl section.
// OpenTitan IPs depend on this package even when EnableRacl=1'b0.
// Re-run 'make generate' to regenerate after changing the spec.

// EnableRacl=0  NrRaclRoles=2  NrRaclPolicies=2  NrCtnUidBits=16
// RACL disabled — types required for compilation, logic tied to 0

package top_racl_pkg;
  localparam int unsigned NrRaclRoles    = 2;
  localparam int unsigned NrRaclPolicies = 2;
  localparam int unsigned NrCtnUidBits   = 16;

  // Binary-encoded RACL role
  typedef logic [$clog2(NrRaclRoles)-1:0] racl_role_t;
  // One-hot encoded role permission vector
  typedef logic [NrRaclRoles-1:0]         racl_role_vec_t;

  // Per-register read/write permission bitmask
  typedef struct packed {
    logic [NrRaclRoles-1:0] read_perm;
    logic [NrRaclRoles-1:0] write_perm;
  } racl_policy_t;

  // Policy selector index
  typedef logic [$clog2(NrRaclPolicies)-1:0] racl_policy_sel_t;
  // Array of policies (indexed by policy selector)
  typedef racl_policy_t racl_policy_vec_t [NrRaclPolicies];

  // RACL range type — maps address ranges to policy selectors
  // Used by spi_host_window.sv and other register tops with windowed access
  typedef struct packed {
    logic [top_pkg::TL_AW-1:0] base;
    logic [top_pkg::TL_AW-1:0] limit;
    racl_policy_sel_t           policy_sel;
    logic                       enable;
  } racl_range_t;

  // RACL denial log entry
  typedef struct packed {
    logic                       valid;
    logic [top_pkg::TL_AW-1:0]  request_address;
    racl_role_t                 racl_role;
    logic                       overflow;
    logic [NrCtnUidBits-1:0]    ctn_uid;
    logic                       read_access;
  } racl_error_log_t;

  // Default (all-deny) policy — used to tie off unconnected policy inputs
  parameter racl_policy_t RACL_POLICY_DEFAULT = '{
    read_perm:  '0,
    write_perm: '0
  };

  parameter racl_policy_vec_t RACL_POLICY_VEC_DEFAULT = '{default: RACL_POLICY_DEFAULT};

  // Extract RACL role from TLUL a_user.rsvd bits
  function automatic racl_role_t tlul_extract_racl_role_bits(
    logic [top_pkg::TL_AUW-1:0] rsvd
  );
    return racl_role_t'(rsvd[$bits(racl_role_t)-1:0]);
  endfunction

  // Extract CTN UID from TLUL a_user.rsvd bits
  function automatic logic [NrCtnUidBits-1:0] tlul_extract_ctn_uid_bits(
    logic [top_pkg::TL_AUW-1:0] rsvd
  );
    return rsvd[NrCtnUidBits-1:0];
  endfunction

endpackage : top_racl_pkg
